mongodb/mongo-swift-driver

- Package.resolved
- Sources/MongoSwift/BSON/BsonValue.swift
- Sources/MongoSwift/Client.swift
- Sources/MongoSwift/Collection.swift
- Sources/MongoSwift/Database.swift
- Tests/MongoSwiftTests/DatabaseTests.swift
This adds an `IntType` protocol which `Int`, `Int32`, and `Int64` conform to. This will allow users to pass in any of the three types.
Also added a few options initializers in places we forgot them the first time around.
> Add missing convenience initializers

- Sources/MongoSwift/Cursor.swift
- Tests/MongoSwiftTests/CollectionTests.swift
This adds a method to get the error that occured while iterating the cursor, if any. Also adds a `nextOrError` throwing method for iterating the cursor if you don't want to have to remember to check the cursor at the end. this still feels kind of weird so if you have any other ideas let me know... but at least for now this is better than just printing out the error message
> Add a getError method and a way to iterate+throw for cursors

- Tests/MongoSwiftBenchmarks/BenchmarkUtils.swift
- Tests/MongoSwiftBenchmarks/BsonBenchmarks.swift
- Tests/MongoSwiftBenchmarks/DocumentBenchmarks.swift
- Tests/MongoSwiftBenchmarks/benchmark.py
This adds an extension to `XCTestCase` to provide custom time measurement code. The time is calculated by taking the difference in system uptime (the same way as in the built-in `measure` functionality.)
While by default benchmarks will now use 100 iterations, I have adjusted the number  in various cases better match the spec requirements that:
- iterations should loop for at least 1 minute cumulative execution time
- iterations should stop after 100 iterations or 5 minutes cumulative execution time, whichever is shorter
Note that this makes the total benchmark execution time far longer, as there are now 13 benchmarks each running for a minimum of 1 minute. 
This also adds a python script to read benchmark output from stdin and store it in a dictionary like this:
`{'testRunCommand': …
> Add custom measurement code for benchmarks, and script to parse results

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/BSON/BsonValue.swift
- Sources/MongoSwift/Client.swift
- Sources/MongoSwift/SDAM.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
Still TBD exactly what we want the API for enabling and disabling monitoring to look like. I've included what I think is at least a clearer interface than having `enableMonitoring` behave differently depending on if it's been called already, but as we talked about yesterday, it's not really clear why someone would want to be switching monitoring on and off repeatedly. anyway, while we figure that out there is a lot else here to review.
I've added a basic test based on [this](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/tests/monitoring/standalone.json) spec test. basically checking that the events come in the correct order and contain the values/descriptions we expect. I think the rest of the tests would require a mock server, or support for …
> Add support for SDAM monitoring

- Makefile
- Package.resolved
- README.md
- Tests/MongoSwiftBenchmarks/BenchmarkUtils.swift
- Tests/MongoSwiftBenchmarks/BsonBenchmarks.swift
- Tests/MongoSwiftBenchmarks/DocumentBenchmarks.swift
- Tests/MongoSwiftTests/ClientTests.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
- add_json_files.rb
Changes:
1. `make` no longer generates an `.xcodeproj` file. Discovered by accident that don't need it for building/testing from command line, just `swift build` will do, so may as well remove it to speed up the build process, unless you had some reason for putting it there? 
2. Add a `project` target to the `Makefile`, which generates the `.xcodeproj` file and then edits it using the ruby script to add corresponding `.json` files to the correct targets. Since we have two separate targets, this required handling each folder in `Tests/Specs` separately... perhaps we should consider moving all the non-benchmark specs into a subdirectory so we can just add all the files from that at once, and not have to add a line to the ruby script every time we add more specs.
3. Add methods to each test …
> SWIFT-68 Make building and testing work both in command line and Xcode, and update README

- Sources/MongoSwift/Client.swift
- Sources/MongoSwift/Collection.swift
- Sources/MongoSwift/Cursor.swift
- Sources/MongoSwift/Database.swift
- Tests/MongoSwiftTests/ClientTests.swift
While the pointers were already technically optional because we created them using [`init?(bitPattern: Int)`](https://developer.apple.com/documentation/swift/opaquepointer/1688016-init), initializing with `bitPattern: 1` never fails. This meant that in cases where assigning a real pointer failed for whatever reason, we would try to free a value at `0x0000000000000001`, causing libmongoc to crash. 
This change makes it so that if we fail to set the pointer to a real value, we won't try to free it.
I also moved the nil-ing out of `self._client`s to the top of each `deinit` so we do it even if we return early because the main pointer is nil. though actually I'm not sure if we even really need to nil out the client at all - shouldn't ARC take care of it and know whether to call …
> SWIFT-70 Make OpaquePointers to libmongoc types optional to prevent freeing unset values

- Sources/MongoSwift/BSON/BsonDecoder.swift
- Sources/MongoSwift/BSON/BsonEncoder.swift
- Sources/MongoSwift/BSON/CodablePrimitives.swift
- Sources/MongoSwift/BSON/Codec.swift
- Tests/MongoSwiftTests/CodecTests.swift
Ok, here is phase one of this. 
It supports decoding a `Document` (which you could create by hand, or from data using our various initializers) into a `Decodable` `struct` or `class`. 
I've tried to stay as close as possible to how the `JSONEncoder` works, and a lot of this is essentially copy-paste from there - plus introducing some generic functions to reduce the ridiculous amount of code duplication... lol. 
So I think phase two will be that we mark all our custom types as `Decodable` and add `init(from decoder: Decoder)` for them.
I have various comments to make inline, but one large point on the numbers stuff we've been discussing: I realized that our conversation about how you'd store various non-BSON numbers was more about how to properly encode numbers to BSON without loss, vs. …
> SWIFT-69 Basic decoder implementation 

- Sources/MongoSwift/BSON/BsonEncoder.swift
- Sources/MongoSwift/Client.swift
- Sources/MongoSwift/Collection.swift
- Sources/MongoSwift/Database.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/ReadWriteConcern.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/Specs/read-write-concern/read-write-concern.rst
- Tests/Specs/read-write-concern/tests/README.rst
- Tests/Specs/read-write-concern/tests/connection-string/read-concern.json
- Tests/Specs/read-write-concern/tests/connection-string/write-concern.json
- Tests/Specs/read-write-concern/tests/document/read-concern.json
- Tests/Specs/read-write-concern/tests/document/write-concern.json
- Implement `ReadConcern` type wrapping a `mongoc_read_concern_t`
- Allow `ReadConcern` to be specified when creating a `MongoClient`, `MongoDatabase`, or `MongoCollection` and for commands that support it 
- Add a new `skipFields` property to the `BsonEncodable` protocol allowing user to specify field names that should be omitted when using the default `encode(to encoder: BsonEncoder)` implementation. This is useful since we want to append `ReadConcern`s to options documents differently than the other fields.
> SWIFT-29 Implement ReadConcern type

- Sources/MongoSwift/BSON/BsonValue.swift
- Tests/MongoSwiftTests/DocumentTests.swift
As we discussed earlier, this is necessary if we want all BSON types to be `Codable`.
> SWIFT-85: Add a custom RegularExpression type

- Sources/MongoSwift/BSON/BsonValue.swift
- Sources/MongoSwift/BSON/Document.swift
- Tests/MongoSwiftTests/DocumentTests.swift
Rather than assuming the value will fit, this checks if it will first and throws an error if not.
> Prevent a fatal error when encoding an Int too large for an Int32

- Sources/MongoSwift/BSON/BsonDecoder.swift
- Sources/MongoSwift/BSON/BsonEncoderNew.swift
- Sources/MongoSwift/BSON/BsonValue.swift
- Sources/MongoSwift/BSON/CodableNumber.swift
- Sources/MongoSwift/BSON/Document+Codable.swift
- Tests/MongoSwiftTests/CodecTests.swift
This is all on top the `BsonDecoder` PR so hold off on reviewing til that's in.
To make the review process easier for switching to the new encoder, I've written this implementation in its own file and temporarily named it `BSONEncoder`(instead of `BsonEncoder`). The old encoder still exists and all of the options types are encoded with it. 
In a second PR to follow this one, I will remove the old encoder and replace all usages of it with this new one, in the process making all of our options types `Encodable`.
> SWIFT-77 Rewrite BsonEncoder to conform to Encoder protocol 

- Sources/MongoSwift/Collection.swift
`upsertedId`, if present, will always be a BSON type, so we should use `BsonValue?` rather than `Any`.
> SWIFT-114 Use a BsonValue? rather than Any for UpdateResult.upsertedId

- Package.resolved
- Sources/MongoSwift/Collection.swift
- Sources/MongoSwift/Database.swift
- Tests/MongoSwiftBenchmarks/DocumentBenchmarks.swift
- Tests/MongoSwiftTests/CollectionTests.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
cc @jsflax
The compiler generates a warning if you don't assign the return value of a non-void function to something. Adding the `@discardableResult` attribute tells the compiler to ignore that. [docs on Swift attributes](https://docs.swift.org/swift-book/ReferenceManual/Attributes.html)
This is useful in cases where a user may not care about the results, and saves them having to assign the return values to `_`. You can see several examples of this in the tests I modified. 
Let me know if you think I missed any methods that have negligible results, or if you think we should still be forcing users to acknowledge the return values of any of the methods I modified.
> SWIFT-73 Add @discardableResult to non-void functions with negligible return values

- Sources/MongoSwift/BSON/Document.swift
- Tests/MongoSwiftTests/DocumentTests.swift
We want copy-on-write behavior for `Document`s, and we implemented this already for when values are set by using `isKnownUniquelyReferenced` on the backing `DocumentStorage`. 
However, I forgot to add the same check for this new mutating function, `merge`, which can lead to some unexpected behavior like this:
```swift
let a: Document = ["x": 1]
var b = a
try b.merge(["y": 2])
// a is now  ["x": 1, "y": 2]
```
This fixes that issue by performing the same `isKnownUniquelyReferenced` check before merging in a new document.
> Fix mutation bug with `Document.merge`

- Sources/MongoSwift/Client.swift
- Sources/MongoSwift/Collection.swift
- Sources/MongoSwift/Database.swift
- Sources/MongoSwift/ReadWriteConcern.swift
Ugh... more things that should be public but weren't. I think we should enable [this linter rule](https://github.com/realm/SwiftLint/blob/master/Rules.md#explicit-acl) requiring explicit access control levels? We have a bunch of minor linter violations I have been meaning to address anyway so I just opened [SWIFT-115](https://jira.mongodb.org/browse/SWIFT-115) to deal with that. 
Anyway, this gets rid of the special logic for encoding `ReadConcern`s as libmongoc will already take care of that for us, and makes `ReadConcern` `Codable` so we can encode it with the rest of the options. 
Also did some refactoring of `ReadConcern` to pull out a couple of the protocols into extensions. unfortunately we can't do this with `Codable` because `required init`s for classes have to be in the class …
> SWIFT-108 Refactor how ReadConcerns are encoded

- Sources/MongoSwift/ReadWriteConcern.swift
Quick fix for some inconsistency pointed out by @jmikola.
> Move `ReadConcernLevel` inside of `ReadConcern`

- Tests/MongoSwiftTests/CrudTests.swift
We skipped the delete + collation tests before because of [CDRIVER-2527](https://jira.mongodb.org/browse/CDRIVER-2527). A fix was included in libmongoc 1.10, so we no longer need to skip them.
> SWIFT-106 Enable deleteOne-collation and deleteMany-collation CRUD tests

- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/ReadConcern.swift
- Sources/MongoSwift/WriteConcern.swift
https://jira.mongodb.org/browse/SWIFT-148
> SWIFT-148: WriteConcern.description should return empty string on error

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
https://jira.mongodb.org/browse/SWIFT-143
I believe this covers all of the relevant helper methods currently in the driver:
* `MongoDatabase.runCommand()`
* `MongoCollection.aggregate()`
* `MongoCollection.count()`
* `MongoCollection.distinct()`
* `MongoCollection.find()`
Per the database, collection, and index enumeration specs, those operations must be executed on a primary server (unless connected to a secondary in standalone mode). In any event, they do not use a read preference.
> SWIFT-143: ReadPreference option for core classes and operations

- Sources/MongoSwift/BSON/BsonValue.swift
- Tests/MongoSwiftTests/DocumentTests.swift
https://jira.mongodb.org/browse/SWIFT-154
> SWIFT-154: Int should encode as Int32 or Int64 as needed

- Sources/MongoSwift/BSON/BsonValue.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/WriteConcern.swift
- Tests/MongoSwiftTests/CrudTests.swift
This adds unimplemented methods for bulkWrite, find and modify ops, and the new count API, plus associated structs.
> SWIFT-137 Sketch remainder of CRUD API

- README.md
`.target()` is consistent with current examples in https://swift.org/package-manager/. This is something I noticed while testing https://github.com/mongodb/mongo-swift-driver/pull/94 for [SWIFT-157](https://jira.mongodb.org/browse/SWIFT-157).
> Replace Target() with .target in Package.swift example

- Development.md
Document how symbolicate-linux-fatal tool from https://github.com/apple/swift/pull/4479 can be used to add symbols to backtraces on Linux
> Instructions for adding symbols to Linux backtraces

- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
This fills out the API sketch and implements the corresponding CRUD tests. I plan on adding more test cases tomorrow in `MongoCollectionTests` to check that nothing catastrophic happens when using the options the CRUD tests don't cover, but I figured I would put up what I have so far.
I think the options encoding solution is pretty good: I've created a `private class FindAndModifyOptions` wrapping a `mongoc_find_and_modify_opts_t`. Each of the Swift options `struct`s conforms to the `FindAndModifyOptionsConvertible` protocol, which means it knows how to represent itself as a `FindAndModifyOptions`. The private `findAndModify` method that we route all the public API methods through can then just do the conversion right before it sends the command.
> SWIFT-146: Implement findAndModify API

- Sources/MongoSwift/BSON/BsonEncoder.swift
- Sources/MongoSwift/BSON/BsonValue.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCollection+Write.swift
This is a pretty straightforward change. The `BsonValue` protocol's `encode` method now takes in a `DocumentStorage` wrapping an `UnsafeMutablePointer<bson_t>`, rather than the pointer directly. 
This did require changing `DocumentStorage` from `internal` to `public`, but we expose no methods or properties on it, so at least it's far more opaque to the user than the pointers were.
> SWIFT-163 Use DocumentStorage rather than pointers in BsonValue protocol

- .swiftlint.yml
- .travis.yml
- Makefile
- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/BSON/AnyBsonValue.swift
- Sources/MongoSwift/BSON/BsonDecoder.swift
- Sources/MongoSwift/BSON/BsonEncoder.swift
- Sources/MongoSwift/BSON/BsonValue.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/ReadPreference.swift
- Sources/MongoSwift/WriteConcern.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftBenchmarks/DocumentBenchmarks.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
- I opted into and disabled various rules in `.swiftlint.yml`. I also excluded the `Tests/` directory because it has like a million violations (mostly about line length) that I will fix some other time. 
- I edited `.travis.yml` to run `swiftlint` on OS X before building
- `make lint` now runs `swiftlint autocorrect` first
- correct various linting violations throughout `Sources/MongoSwift`
> SWIFT-115 Clean up linting

- .travis.yml
OS X builds seem to now work for whatever reason. Reenabling those and adding `SWIFT_VERSION`  as per [swiftenv instructions](https://swiftenv.fuller.li/en/latest/integrations/travis-ci.html) to test both Swift 4.0 and 4.1.
> SWIFT-138 Test both Swift 4.0 and Swift 4.1 on Travis

- Sources/MongoSwift/BSON/BsonEncoder.swift
- Sources/MongoSwift/BSON/BsonValue.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoError.swift
- We already had a `DocumentIterator` type wrapping a `bson_iter_t` to support `Document` being a `Sequence`, so I have repurposed it to be a more general wrapper we can use throughout the BSON library anytime we need to iterate, including in the `BsonValue` protocol. 
I cleaned up some other things along the way, like converting a lot of precondition failures throughout the BSON library to errors now that the `BsonValue` method for reading from an iterator can throw. I think this will make it a lot easier when we are reasoning about document validation and where crashes can occur.
> SWIFT-110 Hide bson_iter_t and refactor iterator code

- README.md
I think the error we experienced the other day relates to this example not matching the minimum deployment requirements of our pod. Instead, we should show a working example, and one that does not target iOS to boot.
> Update README to provide working example Podfile

- .swiftlint.yml
- .travis.yml
- Sources/MongoSwift/BSON/BsonDecoder.swift
- Sources/MongoSwift/BSON/BsonEncoder.swift
- Sources/MongoSwift/MongoSwift.swift
- Sources/MongoSwift/ReadPreference.swift
this corrects the violations I was missing before w/ old version of swiftlint.
it seems that travis hasn't upgraded to including the newest swiftlint yet, so I guess we can just catch these rule violations locally for now...
> Correct linting violations and update travis XCode version

- Package.resolved
- Package.swift
This actually wasn't necessary for the assertions I needed in https://github.com/mongodb/mongo-swift-driver/pull/97, but it didn't seem to break anything in our existing tests either.
> Upgrade Nimble to 7.3.0

- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
This builds on the work in SWIFT-189 to add a server version method to `MongoClient`. 
Basically, for the server version dependent tests we now get the version of the server and compare it to the min/max in the files. 
While I was in there I also did some code cleanup to get rid of unneeded try/catches, simplify file parsing by using a `BsonDecoder`, etc.
> SWIFT-94 Filter tests by current server version

- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Tests/MongoSwiftTests/DocumentTests.swift
This adds a `mapValues` method similar to [Dictionary's](https://developer.apple.com/documentation/swift/dictionary/2995348-mapvalues).
This also overrides the default `filter` implementation (which we got from conforming to the `Sequence` protocol).
Before the signature was 
```swift
public func filter(_ isIncluded: (Element) throws -> Bool) rethrows -> [Element]`
```
and now it's
```swift
public func filter(_ isIncluded: (Element) throws -> Bool) rethrows -> Document
```
We have default `map` and `reduce` implementations already from conforming to `Sequence`.
I also added `isEmpty` to go along with `count`, since it seems to be more idiomatic.
I'm going to dig further through the `Dictionary` docs and source code and potentially open more tickets to see if there are any other methods …
> SWIFT-158 Add filter and mapValues methods to Document

- Sources/MongoSwift/BSON/BsonValue.swift
- Tests/MongoSwiftTests/BsonValueTests.swift
- Tests/MongoSwiftTests/XCTestManifests.swift
This adds a new failable initializer for `Decimal128`, which validates the string by testing `bson_decimal128_t` initialization. 
It seemed to me that it should be an alternate initializer, differentiated by the argument label `ifValid`, so we don't force the performance penalty in unneeded cases.
I thought a failable initializer was more appropriate than throwing (as we do from some other initializers), reasons being that:
1) there is only one very opaque error we would throw from here ("invalid decimal128 string") 
2) this feels more consistent with other Swift methods for parsing types from strings, for example [Int](https://developer.apple.com/documentation/swift/int/2927504-init) and [Data](https://developer.apple.com/documentation/foundation/data/1780388-init).
> SWIFT-89 Add failable initializer for Decimal128

- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Tests/MongoSwiftTests/Document+SequenceTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/XCTestManifests.swift
I use map/filter in these methods so this is on top of [SWIFT-158](https://github.com/mongodb/mongo-swift-driver/pull/108).
there are a number of methods that come along with the sequence protocol such as `dropFirst`, `dropLast`, `prefix`, etc. that return subsequences. By default, the type of these subsequences is `[whatever your iterator returns]`, meaning we would return a`[(String, BsonValue?)]`.
Swift's `Dictionary` provides custom implementations of the `SubSequence` related methods, so that you get a new `Dictionary` back rather than an `[Dictionary.Element]`. This does the same for `Document`s.
> SWIFT-195 Make Document SubSequence type a Document

- Examples/Kitura/Package.resolved
- Examples/Kitura/Package.swift
- Examples/Kitura/Sources/KituraExample/main.swift
- Examples/Vapor/Package.resolved
- Examples/Vapor/Package.swift
- Examples/Vapor/Sources/VaporExample/main.swift
- Examples/loadExampleData.sh
These are the most basic examples you can have for using these services with MongoDB. Use the `loadExampleData.sh` script to insert the expected data, and then each of the examples run a server on `localhost:8080` with a single route `/kittens` provided
> SWIFT-210: Add very basic Kitura and Vapor examples

- .travis.yml
- README.md
This will enable us to take advantage of newly added methods for overwriting fixed-length types in place ([SWIFT-200](https://jira.mongodb.org/browse/SWIFT-200)).
Since we have no way of requiring a particular libmongoc version currently, Travis is the only thing we need to change.
I have also updated the README to instruct users to install 1.13. while our latest release 0.0.3 doesn't actually require it, I fear we will forget to update this minimum version whenever we release 0.0.4, so better to just do it now.
> Use libmongoc 1.13

- .travis.yml
- README.md
- Sources/MongoSwift/BSON/BsonValue.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/BSON/Overwritable.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
Alright, round 2 now that I resolved my unique reference issues.
I moved all the logic for setting a value on a document to a private `setValue` method, please pay attention in particular to the logic there... I think it makes sense re: when we do or don't need to copy underlying storage and overwrite values vs. make new docs, but a sanity check is appreciated.
> SWIFT-196 Check if a key exists before setting it, and overwrite existing keys

- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoError.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/Specs/crud/tests/write/bulkWrite-collation.json
- Tests/Specs/crud/tests/write/bulkWrite.json
- Tests/Specs/crud/tests/write/insertMany.json
This refactors `insertMany()` a bit to be consistent with `bulkWrite()`. We introduce a `MongoError.insertManyError`, which contains an optional `InsertManyResult`.
This also syncs write tests from https://github.com/mongodb/specifications/pull/399, which test for continue-on-error behavior. Additionally, bulkWrite collation tests have been pulled in (and pass). CRUD spec read tests have not been synced due to new count helpers not being implemented (see: [SWIFT-227](https://jira.mongodb.org/browse/SWIFT-227)).
> Refactor insertMany and test CRUD continue-on-error behavior

- Development.md
Personally, I use Neovim, but the added info should work for Vim as well (actually, I think both of the mentioned things were made for Vim).
Finding a spot for tossing in the information about getting proper syntax and indenting for Swift in Vim was a bit of a challenge. I put it under 'Things to Install' since it is probably something you _need_ to install if you are indeed using Vim or Neovim, but other suggestions are welcome.
> Add Neovim/Vim related info to Development.md

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/WriteConcern.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
[SWIFT-201](https://jira.mongodb.org/browse/SWIFT-201)
This PR finds places in the entire codebase where we should probably be using `guard` instead of an `if` statement.
Generally speaking, it seems like `guard` should be used to catch or, _guard_ against exceptional violations of (an) assumption(s) or invariant(s) in the rest of the current scope. Usually, this is involved with condition checks at the beginning of functions or protecting oneself from exceptional failures, e.g., calls to `mongoc_*` functions. Therefore, there may be a few cases where a `guard` is added for something that is not an explicit failure.
I've used the above idea to determine when to use `guard`. Since I essentially looked through the entire codebase, it is possible that I have missed some cases. If you think …
> SWIFT-201: Refactor "if failure" conditions with guard statements

- .swiftlint.yml
- Examples/Kitura/Sources/KituraExample/main.swift
- Examples/Vapor/Package.swift
- Examples/Vapor/Sources/VaporExample/main.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+Write.swift
[SWIFT-236](https://jira.mongodb.org/browse/SWIFT-236)
This PR just fixes some linter issues we were not catching because of a slight issue with our Travis configuration that was ignoring warnings. That issue will be fixed as [SWIFT-237](https://jira.mongodb.org/browse/SWIFT-237).
This PR also renames `enabled_rules` to `opt_in_rules`, since `renamed_rules` will be removed, so we might as well do this now and not deal with issues later.
> SWIFT-236: Fix linter issues

- .travis.yml
[SWIFT-237](https://jira.mongodb.org/browse/SWIFT-237)
Before, our Travis configuration for running `swiftlint` would only fail the build if we had 'serious' violations. This means that if we had warnings that `swiftlint` deemed not 'serious', then we would have a successful exit code of 0, and Travis would not fail the build. This PR adds the `--strict` command line option for `swiftlint` to the Travis configuration, making it so that warnings are treated as errors and therefore give a non-zero exit code. We should not be able to catch linter issues introduced as part of a PR.
This PR is a little weird. Technically, the fix for the things causing the linter to fail is part of #131, so this is somewhat blocked on that, and furthermore, we needed this branch to fail so that we can confirm …
> SWIFT-237: Fix .travis.yml to fail whenever swiftlint has errors OR warnings

- Sources/MongoSwift/BSON/BSONValue.swift
Due to reasons we've yet to exactly determine, the driver will not build in Swift 4.2 in some cases due to an error about BSON_TYPE_CODE not being defined. This switches to using our own BSONType enum (which we should've been doing in the first place) and fixes the compilation errors in 4.2.
> SWIFT-239 use BSONType instead of libbson equivalent

- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/BSONValueTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
[SWIFT-226](https://jira.mongodb.org/browse/SWIFT-226)
This PR adds a convenience function, `bsonEquals` that lets the caller compare two arbitrary `BSONValue`s. This does _not_ add `Equatable` conformance to `BSONValue`, because this would cause us to provide an `Equatable` conformance to all arrays. I, or @kmahar can provide further detail on this if necessary.
This PR also adds many test cases for checking the code paths through `bsonEquals`, but does not check for `preconditionFailure`s, since these cause the program, including the tests, to halt. There is apparently [a way](https://www.cocoawithlove.com/blog/2016/02/02/partial-functions-part-two-catching-precondition-failures.html) to get around this, but it is apparently very hacky.
I've included some comments on my own patch here, …
> SWIFT-226: Provide a way to compare equality of BSONValues

- Development.md
[SWIFT-246](https://jira.mongodb.org/browse/SWIFT-246)
This is just something small I noticed when I was trying to upgrade to version 1.13.0 for the `mongo-c-driver` for the sake of doing [SWIFT-200](https://jira.mongodb.org/browse/SWIFT-200).
This should fix the link for the `README` to point to the fragment on our GitHub repository's README. I tested this by rendering the Markdown locally on Safari and clicking through the link.
I tried looking to see if we had a `README.md` hosted up on the `https://mongodb.github.io/mongo-swift-driver/` site, but I could not find anything promising, since https://mongodb.github.io/mongo-swift-driver/README.md also gave a 404.
Since this seemed like a pretty quick fix, I decided I'd just put up the PR for it before heading home.
> SWIFT-246: README link for "Things to install" in Development.md is broken

- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Codable.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Tests/MongoSwiftTests/CodecTests.swift
[SWIFT-198](https://jira.mongodb.org/browse/SWIFT-198)
This PR replaces instances where we use subscript-setting in a throwing function with `setValue()`. This should help avoid `preconditionFailure`'s and instead propagate a non-fatal error for the end-user.
There were some instances of functions that were declared as `rethrows`. From my understanding, these functions only throw if their argument which is a function/closure throws itself, so we cannot use `setValue()` without marking those function as `throws`. This was enough of a change that I figured it shouldn't be included in this ticket. Plus, these were implemented in conformance to `Sequence`, and I believe marking them as `throws` would break the conformance.
As usual with these kinds of PRs, let me know if you think I have …
> SWIFT-198: Use setValue where possible rather than subscript setter

- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Overwritable.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-200](https://jira.mongodb.org/browse/SWIFT-200)
This PR has a fairly self-explanatory title. It extends `ObjectId`, `Timestamp` and `Datetime` with overwrite methods so that they can conform to `Overwritable`. Alongside this, it updates the tests in `DocumentTests.swift` to include the new conformances.
This PR also includes some fixes to linter issues in `DocumentTests.swift`, as well as a rename of some variables in the related test cases, which should improve the readability of the test cases.
Is there a way to test this stuff on 32-bit systems? It seems like our Travis configuration does not run on 32-bit systems.
> SWIFT-200: Use libbson overwrite methods for ObjectId, Timestamp, Datetime 

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Codable.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
[SWIFT-199](https://jira.mongodb.org/browse/SWIFT-199)
This PR adds a function to `Document` that is the `get` analog of `setValue()`. This function throws instead of triggering a fatal `preconditionFailure()`, which should help reduce the number of fatal errors. This is implemented via the addition of a throwing function equivalent to `currentValue` of `DocumentIterator`. Eventually, this seemed like the optimal choice, since it lets us package the logic of extracting the current value inside the iterator, where such logic should exist, instead of `Document`.
As usual with these kinds of PRs, let me know if I have missed any instances where we should be using `getValue()`, but this should be all. I used a `git grep` regex to find them all.
> SWIFT-199: Add a throwing getValue method

- Sources/MongoSwift/SDAM.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
[SWIFT-231](https://jira.mongodb.org/browse/SWIFT-231)
This PR adds an ability for us to take a MDB connection string from the environment, defined via `$MDB_CONN_STR`, and use it to determine what `mongod` server to connect to for our tests. This is implemented with some convenience initializers, which lets us implement this ticket in a relatively small diff. Alternative approaches are welcome if this is not 'Swift-y'.
> SWIFT-231: Don't hard-code in port number for tests

- Tests/MongoSwiftTests/BSONValueTests.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/Document+SequenceTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/ReadPreferenceTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
[SWIFT-207](https://jira.mongodb.org/browse/SWIFT-207)
This PR adds a test base class (`MongoSwiftTestCase`) meant to replace our extension to `XCTestCase`. It also introduces changes to migrate the existing test case to use the new base class.
It does not add any new functionality to the new base class.
> SWIFT-207: Create base class for functional tests

- README.md
- Sources/MongoSwift/BSON/Document+Collection.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Tests/MongoSwiftTests/Document+CollectionTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/XCTestManifests.swift
[SWIFT-192](https://jira.mongodb.org/browse/SWIFT-192)
This PR adds `Collection` conformance to `Document`.
This diff is not too big, but this ticket took quite a while due to various and significant issues with trying to get `Collection` conformance working for `Document`!!! I am very happy to finally get this PR out!
Performance improvements for reaching runtime guarantees of `Collection` conformance will be done separately.
I've also refrained from combining `Document+Sequence.swift` with `Document+Collection.swift`, since with the completion of SWIFT-259, I expect a decent amount of LoC increase and I am guessing it would be better to keep them separate for organizational purposes. We can merge them in a later if my guess is wrong.
Finally, I've added some tests that test the methods …
> SWIFT-192: Make Document conform to Collection protocol

- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/TestUtils.swift
Now that @Utagai added a base test class, this was super easy.
Note that this `class func` is called once before each of our separate test classes, i.e. once before `DocumentTests`, once before `CodecTests`, and so on. Since @jmikola wrote `MongoSwift.initialize()` so that repeated calls have no effect, this should be just fine. 
I believe this also removes the need to call `MongoSwift.initialize()` in `LinuxMain.swift`.
> SWIFT-119 Initialize libmongoc before running tests from macOS command line

- Sources/MongoSwift/APM.swift
Just a one line change. Compiles either way, but the compiler starts warning you about this as of 4.1.
> SWIFT-235 Fix UnsafeMutableRawPointer! deprecation warnings in Swift 4.1+

- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/BSONValueTests.swift
- Read timestamp from `bson_oid_get_time_t`
- Expose as `timestamp` within `ObjectId` class
> SWIFT-265: ObjectId should expose timestamp

- Tests/MongoSwiftTests/BSONValueTests.swift
for some strange reason, this test was failing on Linux with Swift 4.2. don't know why. @mbroadst looked at it for a bit but I don't think he figured out the issue. 
anyway, this seems like a weird Swift on Linux bug, so I've modified the test to check for basically the same thing but in a different way.
@Utagai, including you so you can verify that I correctly interpreted what this assertion was trying to check?
> Fix Linux + Swift 4.2 failure

- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-279](https://jira.mongodb.org/browse/SWIFT-279)
Swift `Date`s use `TimeInterval`s to represent units of time. `TimeInterval` is simply a typealias of `Double` and is stored in terms of seconds. Our `BSONValue` Dates convert to milliseconds for interoperability with the BSON date type, but it loses precision when doing so in a couple of places. This PR fixes those precision errors.
> SWIFT-279 Fix loss of precision when initializing Date BSONValue from msSinceEpoch

- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/Document+SequenceTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
[SWIFT-241](https://jira.mongodb.org/browse/SWIFT-241)
This PR replaces the standard `equal` Nimble matcher with our custom `bsonEqual` matcher in all existing tests.
> SWIFT-241 Replace pre-existing test code to use the new bsonEqual Nimble matcher

- Sources/MongoSwift/BSON/Document.swift
[SWIFT-270](https://jira.mongodb.org/browse/SWIFT-270)
This PR moves all the non-stored properties and functions out of the `Document` struct declaration into separate extensions, one for public API and one for internal/private functionality.
The original ticket suggests simply moving the internal properties/functions out of the declaration and keeping the public API in, but I've moved everything out so as to keep the declaration as bare bones as possible. This maintains the desired readability improvements while also minimizing how much code is duplicated in conditional declarations (which will occur when adding `@dynamicMemberLookup` in SWIFT-219). 
The git diff for this is pretty weird, but all I did was move code around to different extensions.
> SWIFT-270 Move internal Document methods to a separate extension

- Package@swift-4.2.swift
Adds a new version-specific `Package.swift`. Without this, `-swift-version 4` is still passed to the compiler, which then thinks we are in 4.1 when we do `#if swift` version checks. what's confusing about this to me is that even without this change, one can still successfully compile and use Swift 4.2 features in the code, for ex. I just tried this with Swift 4.2's new `CaseIterable` protocol. the version checks just don't work as one would expect.
for now anyway, this seems to be the standard way to still support 4.0 while adding support for 4.2.
> Add 4.2 version of Package.swift

- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
[SWIFT-253](https://jira.mongodb.org/browse/SWIFT-253)
This PR adds new class computed property `testDatabase` to `MongoSwiftTestCase`, which returns the name of the database that particular test case runs against, and replaces all hard-coded database names in tests to use it. 
Since it is static/class, all instances of the same test case share the same test database. It seemed like that was already assumed when the cases were written (e.g. teardown runs in a static context), so I preserved that property here.
> SWIFT-253 Make test database name accessible from the base class

- Sources/MongoSwift/BSON/Document.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-219](https://jira.mongodb.org/browse/SWIFT-219)
This PR adds conditional support for the `@dynamicMemberLookup` attribute to `Document` for versions of swift >= 4.2. This allows one to access members of a document via dot-notation.
> SWIFT-219 Add @dynamicMemberLookup to Document

- Sources/MongoSwift/BSON/AnyBSONValue.swift
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Codable.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/Document+SequenceTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
[SWIFT-278](url)
This PR updates `BSONValue.from(iterator)` to return `Self` instead of `BSONValue`, which is semantically nicer. Originally, we returned `BSONValue` to facilitate conversion of deprecated BSON 
types to other ones, but that is handled elsewhere now.
Due to some weird issues involving `NSNull` on Linux, this PR also introduces a new type to represent BSON null values: `BSONNull`.
> SWIFT-278 BSONValue.from(iterator) should return Self, not BSONValue

- Sources/MongoSwift/BSON/BSONValue.swift
Fixes #174.
#171 deprecates the use of NSNull in favour of BSONNull
Unfortunately, it's not possible to instantiate BSONNull outside the MongoSwift module because the automatically synthesised initialiser is internal.
Adding a simple public init() { } would solve this issue.
> Added public initializer to BSONNull

- Sources/MongoSwift/BSON/Document.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-191](https://jira.mongodb.org/browse/SWIFT-191)
**NOTE** This PR can only be merged after [the PR for SWIFT-193](https://github.com/mongodb/mongo-swift-driver/pull/145). The excessive amounts of commits are mostly from that branch, so after it is merged I'll rebase and almost all of them should go away. As a result of this, this PR's diff is basically contaminated by the diff from SWIFT-193. It's probably best to wait for SWIFT-193 to be merged before even trying to review this PR, but if you'd like, the two files of interest are `Document.swift` and `DocumentTests.swift`.
This PR adds functionality to `Document` such that users can now supply a default value to the `subscript()` function. An example of this can be found in `DocumentTests.swift`, at the bottom, but here is a …
> SWIFT-191: Add a way to provide a default value when looking up a key in a Document

- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/BSONValueTests.swift
[SWIFT-293](https://jira.mongodb.org/browse/SWIFT-293)
This PR ensures `bsonEquals` checks that the size of two arrays is the same before comparing, fixing a bug where arrays that were prefixes of others could be considered equal.
> SWIFT-293 Fix bsonEquals not working for arrays of different length

- Sources/MongoSwift/BSON/AnyBSONValue.swift
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-281](https://jira.mongodb.org/browse/SWIFT-281)
This PR adds two options for specifying a `DateDecodingStrategy` and a `UUIDDecodingStrategy` on a given `BSONDecoder`. 
For `Date`, I mimicked the functionality of `JSONDecoder`'s [strategies](https://developer.apple.com/documentation/foundation/jsondecoder/datedecodingstrategy). I also added a `.bsonDateTime` strategy for when the date is encoded as a BSON datetime. 
The default strategy is `.bsonDateTime`.
For `UUID`, I added the following strategies:
- `.defferredToUUID`: uses `UUID`'s implementation of `init(from: decoder)`
- `.binary`: decodes from a BSON binary type
The default is `.binary` as per the encoding in #162 .
The ticket mentions changing the decoder from `public` to `open`, but I didn't see why that is necessary. …
> SWIFT-281 Allow .uuidDecodingStrategy and .dateDecodingStrategy to be set for BSONDecoder

- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
[SWIFT-206](https://jira.mongodb.org/browse/SWIFT-206)
This PR adds a function to `MongoSwiftTestCase` for generating collection names of the format "`<Test Case>_<Test Name>_<optional suffix>`".
e.g. a namespace for `testListDatabases` would be `test.MongoClientTests_testListDatabases`
> SWIFT-206 Use generated collection names for tests

- Sources/MongoSwift/BSON/AnyBSONValue.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-282](https://jira.mongodb.org/browse/SWIFT-282)
This PR adds the ability to specify encoding strategies for `Date`s and `UUID`s. The strategies for both match their corresponding decoding strategies defined in #176 . 
Also, this PR has some missing comments and has some duplication from the preceding one. Once the other merges, I will rebase this off that and put the pieces together. All of the important implementation is complete.
UPDATE: we now follow `JSONEncoder`'s implementation of the `.custom` date encoding strategy for maintaining interoperability with other encoders. Also, some of the pitfalls of doing it this way were a bit overstated.
Outdated:
However, for the `.custom` strategy, I deviated from the implementation that `JSONEncoder` chose. Ours is defined as …
> SWIFT-282 Allow .uuidEncodingStrategy and .dateEncodingStrategy to be set on BSONEncoder

- .travis.yml
I have it set to download 0.29.3 which is the current latest one. We can manually bump as necessary.
Will eventually cache this in later work.
> Download portable SwiftLint binary on OSX builds instead of using Homebrew

- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
[SWIFT-289](https://jira.mongodb.org/browse/SWIFT-289)
This PR adds public initializers to some public types that don't have them. It also exposes `UUID.init(from binary: Binary)`.
It seems the assumption for the other types that do have public initializers is that the default ACL was public, since the docstrings on all those initializers say they're for convenience. 
e.g.
```
/// Convenience initializer allowing any/all parameters to be optional
```
In reality, these initializers are actually very necessary and are not merely conveniences. The docstrings I added are consistently worded with the old ones but omit "convenience". Let me know if you think I should change the older docstrings and/or the newer ones.
> SWIFT-289 Audit public types to make sure they have public initializers

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-321](https://jira.mongodb.org/browse/SWIFT-321)
This is just a small patch to fix some differences in between the encoding and decoding strategies. The most important change is the refactoring of decoding strategies from `.deferTo<something>` to `.deferredTo<something>`.
> SWIFT-321 Unify decoding and encoding strategies

- Sources/MongoSwift/BSON/AnyBSONValue.swift
- Tests/MongoSwiftTests/BSONValueTests.swift
[SWIFT-255](https://jira.mongodb.org/browse/SWIFT-255)
This PR adds `Hashable` conformance to `AnyBSONValue` by computing the hashValue of the extended JSON representation of the underlying `BSONValue`. 
I originally tried using the `hashValue` of the wrapped `BSONValue` if it was `Hashable` itself, but I was experiencing some collisions (`hashValue` is only likely to be unique among the same types I guess). Instead, I just resorted to using the extended JSON `hashValue` for everything. It may a bit slower as it has to create a temporary document which is then transformed to JSON, but at least it avoids collisions. There is an argument to be made that tolerating collisions is more performant than converting everything to their extended JSON formats, but I'm not really sure if that is the …
> SWIFT-255 Conform AnyBSONValue to Hashable

- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
This makes it so we don't modify the input document(s) in `insertOne` and `insertMany` when they are missing an `_id`. 
Instead, if a doc is missing an `_id`, we make a new document with an `_id` at the start, copy over the data from the original doc, and send the new doc to the server.
> SWIFT-280, SWIFT-334: Improve handling of documents missing _id in insertOne and insertMany

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-316](https://jira.mongodb.org/browse/SWIFT-316)
This PR adds the `.deferredToData` and `.binary` decoding/encoding strategies to `BSONEncoder`. 
I decided upon using `.binary` as the default because, at least in my reading of the spec, that is the type specified for this exact purpose. Also, the waste concerns mentioned in the original ticket are worth avoiding by default, I think.
I also think that `Data` is a good candidate for the `.custom` encoding/decoding strategy, since users may be aware of some structure of their buffers and want to encode it in their own way. Messing around with buffers like that wouldn't be the most Swift-y way to do things, but I feel like it may be useful to some users, especially if they're interfacing with their own C libraries. 
I also think there …
> SWIFT-316 Add a .dataEncodingStrategy and a .dataDecodingStrategy to support storing Data in BSON binary format

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Collection.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/ReadPreference.swift
[SWIFT-261](https://jira.mongodb.org/browse/SWIFT-261)
This PR replaces all `precondition`s and `preconditionFailure`s with `fatalErrors`. 
Comparison:
- In a debug build, `preconditionFailure` is the same as `fatalError`
- In a release build, `preconditionFailure` exits, but does not print a message. `fatalError` does both.
- in an `-Ounchecked` build, the `preconditionFailure` may be skipped. `fatalError` behaves the same.
Because of the silent nature of `preconditionFailure` and the possibility that it doesn't get called in `OUnchecked` builds, I think we should only be using `fatalError`. In the cases where we only want to exit when testing, we should use `assert`. AFAIK there are no such cases outside of the tests where the latter is true in the codebase right now.
> SWIFT-261 Replace preconditions and preconditionFailures with fatalErrors

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/MongoError.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/MongoError+Equatable.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
[SWIFT-144](https://jira.mongodb.org/browse/SWIFT-144) / [SWIFT-300](https://jira.mongodb.org/browse/SWIFT-300)
This PR updates reading CRUD operations to throw errors from the new error hierarchy. (SWIFT-144). As part of that, `InsertMany` now both throws a `.bulkWriteError` and is implemented as a bulk write (SWIFT-300). Also, command failure events have been updated to use the new errors as well.
> Update CRUD API errors to match the new hierarchy

- Examples/Kitura/Sources/KituraExample/main.swift
- Examples/Vapor/Sources/VaporExample/main.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/ReadPreference.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
[SWIFT-301](https://jira.mongodb.org/browse/SWIFT-301) / [SWIFT-302 ](https://jira.mongodb.org/browse/SWIFT-302)/ [SWIFT-303](https://jira.mongodb.org/browse/SWIFT-303) / [SWIFT-305](https://jira.mongodb.org/browse/SWIFT-305)
In this PR:
- `.invalidCollection`, `.invalidClient`, `.invalidUri`, and `.invalidResponse` updated to `.internalErrors` or `.fatalErrors` as necessary (SWIFT-301).
- Most notable change: `MongoDatabase.collection`, `MongoClient.database` no longer throw. They simply `fatalError` when something goes wrong (which it should never).
- `.invalidCursor` converted to new errors as necessary (SWIFT-302)
- The most notable change here involves making the initializer of `Cursor` throw. This way users will be notified of `.invalidArgumentErrors` when creating the cursor …
> Various error migrations

- Sources/MongoSwift/BSON/AnyBSONValue.swift
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/BSON/Overwritable.swift
- Sources/MongoSwift/MongoError.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-304](https://jira.mongodb.org/browse/SWIFT-304)
This PR replaces `bsonEncodeError`, `bsonDecodeError`, and `typeError` with the new error types. 
The `bsonEncodeErrors` which derived from a document growing too large after being appended to were replaced with `.internalErrors`. In general, I don't like using / documenting `.internalErrors` and would prefer to reserve them for unexpected errors. I think they fit this use-case decently well, but I would not be opposed to considering the addition of one more `RuntimeError`, namely `RuntimeError.documentTooLargeError` or `RuntimeError.documentSizeError` (to account for when the document is too small as well). What do you guys think? Would this be too specific?
`bsonDecodeErrors` generally resulted from iterator methods trying to …
> SWIFT-304 Convert bsonEncodeError, bsonDecodeError, typeError to new error types

- Examples/Docker/Dockerfile
- Examples/Docker/Dockerfile.vapor
- Examples/Docker/README.md
- README.md
Added documentation and examples on building `libmongoc` and `libbson` from source on Ubuntu in Docker.
> Documentation and examples on building `libmongoc` and `libbson`

- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/WriteConcern.swift
[SWIFT-307](https://jira.mongodb.org/browse/SWIFT-307)
This PR updates some old `MongoError` invalid argument errors and converts any `.invalidArgumentErrors` that were thrown in the wrong places.
> SWIFT-307 Audit invalid argument errors

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/SDAM.swift
[SWIFT-310](https://jira.mongodb.org/browse/SWIFT-310)
This pr removes the old errors and any references to them, and refactors the new `MongoSwiftError` protocol to be `MongoError`.
> SWIFT-310 Remove old errors

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/BSONValueTests.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoError+Equatable.swift
- Tests/MongoSwiftTests/ReadPreferenceTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
[SWIFT-306](https://jira.mongodb.org/browse/SWIFT-306) / [SWIFT-309](https://jira.mongodb.org/browse/SWIFT-306)
This PR updates any tests that expect an error to explicitly match against the error they expect. As part of that, I discovered a couple of inconsistencies in how the `BSONDecoder` emits errors and have included fixes for that here.
> SWIFT-306 / SWIFT-309: Audit Tests for Errors / Audit Encoder/Decoder Errors

- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-313](https://jira.mongodb.com/browse/SWIFT-313)
> SWIFT-313 Move RegularExpression.nsRegularExpression logic into a new NSRegularExpression initializer

- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-351](https://jira.mongodb.com/browse/SWIFT-351)
> SWIFT-351 Correctly encode strings with multi-byte UTF8 characters

- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/CodecTests.swift
[SWIFT-331](https://jira.mongodb.org/browse/SWIFT-331) / [SWIFT-332](https://jira.mongodb.org/browse/SWIFT-332)
This PR throws errors in the `init(from:)` and `encode(to:)` methods of all driver-introduced BSON types.
The original ticket description calls for only throwing errors when using _non_-`BSONEncoder/Decoder`, but we should actually be throwing whenever execution reaches those two methods. 
The reasons for throwing are:
- A _non_-`BSONEncoder/Decoder` is being used and we currently don't have a standardized output/input yet for all BSON types (original ticket reason)
- `BSONEncoder/Decoder` is being used, but is using the synthesized/default `Codable` conformance
- All the driver-introduced BSON types correspond to BSON primitives, so we should just be reading them straight out …
> SWIFT-331 Throw errors in encode(to:) and init(from:) in driver-introduced BSONValue types

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/CodingStrategies.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/ReadPreference.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
[SWIFT-337](https://jira.mongodb.org/browse/SWIFT-337)
This PR allows users to set the encoding/decoding strategies at the client, database, or collection level. Collections inherit these options from databases, and databases inherit them from clients. They also can be specified when getting/creating a client, database, or collection. 
In implementing this, I defined `DateCodingStrategy`, `UUIDCodingStrategy`, and `DataCodingStrategy`, unifying the encoding/decoding pairs into single cases. This reduces some of the boilerplate for us and for users, and it also restricts users from setting incompatible pairs (e.g. encoding uses `bsonDate`, decoding uses `millisecondsSince1970`). They're defined in `BSONEncoder.swift` arbitrarily.
> SWIFT-337 Support setting of encoding/decoding strategies on client, database, and collection levels

- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/ReadConcern.swift
- Sources/MongoSwift/ReadPreference.swift
- Sources/MongoSwift/WriteConcern.swift
This brings us to 100% documentation on jazzy.
The ReadPreference mode docs were missing (which is what this ticket was initially about), but it appears jazzy now also cares about having documentation for protocol methods (e.g. all the `Sequence` protocol methods I've added docstrings for here), as well as for `deinit`s. I standardized the docstring for all of the `deinit`s - a lot of them mentioned libmongoc/libbson internals which we should avoid talking about in documentation.
> SWIFT-340 Add missing documentation

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Overwritable.swift
- Tests/MongoSwiftTests/BSONValueTests.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/Document+SequenceTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
[SWIFT-356](https://jira.mongodb.org/browse/SWIFT-356) / [SWIFT-352](https://jira.mongodb.org/browse/SWIFT-352)
This PR ensures all BSON types laid out in the bsonspec are correctly round-tripped through `Document` via the bson-corpus spec tests.
The main changes:
- introduction of `BSONUndefined` type
- exposing of `Symbol` and `DBPointer`
- `Decimal128` now stores a `bson_decimal128_t` instead of converting back and forth between strings
- The default (and only public) constructor now is an `init?`, since we cannot avoid constructing the `bson_decimal_128_t` any longer if it's serving as the storage
> SWIFT-356 / SWIFT-352 Round trip all BSONValues correctly

- Sources/MongoSwift/BSON/BSONValue.swift
[SWIFT-379](https://jira.mongodb.org/browse/SWIFT-379)
This PR is a follow up to SWIFT-332. It improves the error message used when the wrong `BSONValue` type is encountered when attempting to decode another (driver-introduced) `BSONValue` type.
As part of this patch, I cleaned up the way errors are decided upon to be more flexible for future changes and also to be more readable.
> SWIFT-379 Improve error message for type mismatches when decoding driver introduced BSON types

- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/SDAM.swift
- Sources/MongoSwift/WriteConcern.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
Deletes our `==` functions anywhere they are just doing the default behavior (comparing all stored properties.)
> SWIFT-297 Use synthesized Equatable where possible

- Package.resolved
- Package.swift
- Sources/MongoSwift/BSON/Document.swift
This method is introduced to overcome limitations around field
access when `bson_t` is treated as an `OpaquePointer`.
> use internal `_bson_get_len` from swift C bson bindings

- Sources/MongoSwift/BSON/AnyBSONValue.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftTests/BSONValueTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
[SWIFT-372](https://jira.mongodb.org/browse/SWIFT-372)
This PR adds `bsonEquals` to the `BSONValue` protocol. It also deprecates the existing `bsonEquals` function.
> SWIFT-372 Add bsonEquals to BSONValue protocol

- .swiftlint.yml
- Sources/MongoSwift/BSON/AnyBSONValue.swift
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/CodableNumber.swift
- Sources/MongoSwift/BSON/Document+Codable.swift
- Sources/MongoSwift/ReadPreference.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/Document+SequenceTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
So apparently you have to tell SwiftLint that you want this rule on for comments....
> Enable trailing whitespace rule in comments

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/ReadPreference.swift
- Sources/MongoSwift/SDAM.swift
- Tests/MongoSwiftTests/DocumentTests.swift
This fixes several memory leaks in the driver. Kudos to @valeriomazzeo for pointing these out in #236.
I've done the following:
* Rename `Document(fromPointer:)` and `DocumentStorage(fromPointer:)` to `Document(copying:)` and `DocumentStorage(copying:)` to make it clearer what their behavior is 
* Add a new `DocumentStorage(stealing:)` initializer that takes over responsibility for the provided `bson_t`, and a `Document(stealing:)` initializer that calls through to it
* Update every place the `fromPointer` initializers were used to call through to the correct new methods 
I also fixed a leak of the `mongoc_uri_t` in the `MongoClient` initializer, and a leak we'd previously identified in SDAM monitoring (SWIFT-294).
> SWIFT-294, SWIFT-394 Fix memory leaks

- .evergreen/config.yml
- .evergreen/find-cmake.sh
- .evergreen/install-dependencies.sh
- .evergreen/run-tests.sh
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
- update evergreen config
- install swift using swiftenv
- add support for skipping tests by topology
- add `find-cmake.sh` script
- use patrick's new numeric helpers to avoid topology issues
- ensure all tests of a commands response use `doubleValue` for `ok`
- skip command monitoring tests on sharded topologies
- reduce to a single mongos if multiple are provided
- add 4.2 and 5.0 variants
- disable macos tests until we can figure out how install without
root permissions
> SWIFT-17: add evergreen linux support

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Overwritable.swift
- Tests/MongoSwiftTests/BSONValueTests.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
[SWIFT-268](https://jira.mongodb.org/browse/SWIFT-268)
As part of this update, I refactored the public `oid` property on `ObjectId` that returns the string representation to `hex`, which is more descriptive. It also aligns with Go driver's `Hex()` and Java driver's `toHexString()`. 
I also refactored `init(fromPointer:)` to `init(copying:)`, similar to the memory leak fix refactors.
> SWIFT-268 Store bson_oid_t in ObjectId rather than creating one each time we need it

- Sources/MongoSwift/BSON/AnyBSONValue.swift
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Fixed redundant `internal` declaration that were triggering warnings on Xcode 10.2
- Updated `AnyBSONValue` conformance to `Hashable`
> Fixed warnings

- .evergreen/config.yml
- .evergreen/install-dependencies.sh
- .evergreen/run-tests.sh
This is dependent on a branch of `swiftenv` on my local github
account to work, that will hopefully be resolved shortly. Other
items of note here are that we only build on the macos-1014 hosts
due to XCode version requirements, and some tricky linker lines
to accommodate rpath linking to libmongoc.
> SWIFT-399: enable evg builds on OSX hosts

- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/Operations/CountOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/Operation.swift
Part 1 of many. This introduces the `Operation` protocol and migrates the non-cursor `MongoCollection` "read" methods to use it.
> SWIFT-373: Introduce Operation protocol, CountOperation, and DistinctOperation 

- Sources/MongoSwift/MongoCollection+Indexes.swift
This is a precursor to the next operations PR for the index methods.
I've done the following:
- update inaccurate documentation (we had writeConcern listed as a parameter everywhere rather than the options type)
-  route all drop and create commands through single methods, that will be converted to operations in the next PR
- remove the `IndexOptions` parameter from `dropIndex(keys:)`. we were already completely ignoring it and there is no way to send the information the options contain to the server. see Friday afternoon conversation in #drivers for some more context.
> Clean up index methods

- Sources/MongoSwift/BSON/Document.swift
Ensures you can only update the Document count from within `Document.swift`.
> SWIFT-405 make Document.count fileprivate(set)

- Tests/MongoSwiftTests/CodecTests.swift
now that we skip this, the compiler prints a warning every time you build/run the tests about how we never reach line 456.
> Comment out skipped test

- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
#248 did some refactoring so that all index creation would go through a single method, and same for dropping indexes. 
This converts those methods into operation types, `CreateIndexesOperation` and `DropIndexesOperation`.
> SWIFT-373 Add CreateIndexes and DropIndexes operations

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/Document+Codable.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/SDAM.swift
fixes what we were talking about earlier with the justifications needing to be in separate lines.
> move SwiftLint disable justification comments into different lines

- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoError.swift
- Tests/MongoSwiftTests/CrudTests.swift
Reimplements all write methods to use the bulk API instead of the libmongoc helpers.
> SWIFT-373 Convert all write methods to use the bulkWrite API

- Sources/MongoSwift/MongoDatabase.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
When refactoring the database methods to be operations, I decided to check if we had all of the correct options available for `createCollection`. turns out we were missing `pipeline`.
I've added it and also a test that exercises all the possible createCollection options to make sure the server accepts them.
> Add pipeline option to createCollection and test all createCollection options

- Sources/MongoSwift/MongoDatabase.swift
Stemming from conversation on SWIFT-373 I fixed one ReadPreference issue there and happened to notice another.
I'm surprised we didn't catch the `MongoDatabase.readPreference` issue. I noticed our tests there are very lackluster and only test the type itself and not setting it on clients/DBs/colls or using it for commands or anything like that. I opened [SWIFT-447](https://jira.mongodb.org/browse/SWIFT-447) about remedying this.
> Fix a couple ReadPreference issues

- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/Operations/CountOperation.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwift/Operations/Operation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/MongoError+Equatable.swift
This PR adds the implementation of client sessions as per the [design](https://docs.google.com/document/d/1n5N8f1Zgzd5Iow5gxiRSoj6FZ8-Gus8I5CUTrW1Gh3s/edit#heading=h.ky3pv4dt04e).
Deviations from the design:
- `session.sessionId` refactored to `session.id`, the "session" prefix seemed redundant
- `session.endSession` -> `session.end` ditto redundancy
- The test plan prescribed performing spec test 9 (ensure all sessions are cleaned up after each test), but without access to the underlying pool this is difficult
- The test plan states that many of the tests should run every function that takes in a session or against every topology with every read preference. This is overkill for what we're implementing. Assuming libmongoc is performing those tests at their level, all we need to do is …
> Swift-28 Implement Sessions

- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/Operations/NextOperation.swift
Adds a `NextOperation` for calls to `mongoc_cursor_next`.
> SWIFT-373 add NextOperation for cursor ops

- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Sources/MongoSwift/Operations/DropCollectionOperation.swift
- Sources/MongoSwift/Operations/DropDatabaseOperation.swift
- Sources/MongoSwift/Operations/RunCommandOperation.swift
This adds a `RunCommandOperation` and switches `runCommand`, `createCollection`, and `dropDatabase` to use it.
> SWIFT-373 Add runCommand operation and switch DB methods to use it

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoSwift.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
Gets rid of the `MongoSwift` class and moves the init/cleanup methods to be free-floating.
> SWIFT-402 Resolve MongoSwift namespace issues

- Sources/MongoSwift/Operations/RunCommandOperation.swift
Per conversation on Slack and on [CDRIVER-3117](https://jira.mongodb.org/browse/CDRIVER-3117), the SDAM spec says:
> The generic command method has a default read preference of mode 'primary'. The generic command method MUST ignore any default read preference from client, database or collection configuration. The generic command method SHOULD allow an optional read preference argument.
so, this was right the first time. very good call on not using this helper for other methods though @mbroadst. I think maybe we will eventually end up with WriteCommandOperation and ReadCommandOperation that call the read/write specific mongoc command helpers.
> Don't use DB default read preference

- Sources/MongoSwift/ClientSession.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
[SWIFT-175](https://jira.mongodb.org/browse/SWIFT-175)
This PR also reworks the previous sessions test so that it's easier for more tests to cover every client/db/collection method that takes in a session.
> SWIFT-175 Causal consistency support

- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
Moves the private `findAndModify` method code to a new `FindAndModifyOperation`.
`FindAndModifyOptionsConvertible` needed to become `internal` so we could use it in that file, and I renamed its `asOpts` methods to `asFindAndModifyOptions` for consistency with our `BulkWriteOptionsConvertible` protocol. 
Similarly, `FindAndModifyOptions` had to become `internal` since its now defined in the new file but used in the original file.
> Convert FindAndModify to use an Operation

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
This defers the creation of `mongoc_database_t`s and `mongoc_collection_t`s to the `MongoDatabase` and `MongoCollection` initializers, respectively.
> SWIFT-377 Refactor DB and collection initializers to take in options rather than libmongoc types

- Sources/MongoSwift/MongoSwift.swift
So I realized we had renamed the actual initialization method to `initializeMongoc`, so I just added an empty `initialize()` method.
I tested this locally, and if you have a call to `MongoSwift.initialize()` you will now get the following compiler warning:
```
/Users/kaitlinmahar/TestProject/Sources/TestProject/main.swift:3:12: warning: 'initialize()' is deprecated: Calling this method no longer has any effect.
MongoSwift.initialize()
^
```
> Add empty deprecated initialize() and deprecated cleanup()

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/Operations/CountOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
This is part of a series of reviews that make up [SWIFT-178](https://jira.mongodb.org/browse/SWIFT-178)
This PR adds `Decodable` conformance to options and result types that will eventually be decoded from JSON spec test files. It also improves the error parser to be more flexible when decoding from server replies.
> SWIFT-178 Conform various options/result types to Decodable

- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/BSON/DocumentIterator.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/Operations/CountOperation.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
- Sources/MongoSwift/Operations/RunCommandOperation.swift
- Sources/MongoSwift/ReadPreference.swift
- Tests/MongoSwiftTests/Document+CollectionTests.swift
- Tests/MongoSwiftTests/DocumentTests.swift
This adds two `withBSONPointer` and `withMutableBSONPointer` methods to `Document`  that can be used to get access to immutable/mutable pointers underlying the document. I've switched to using those everywhere we were just directly using the bson_t pointer before.
Additionally, all errors are now passed in with `withUnsafeMutablePointer` instead of with `&`.
> SWIFT-411 Make pointer access to bson_ts more explicit

- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/DropCollectionOperation.swift
- Sources/MongoSwift/Operations/DropDatabaseOperation.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
[SWIFT-493](https://jira.mongodb.org/browse/SWIFT-493)
> SWIFT-493 Support passing in sessions to "drop" command

- Sources/MongoSwift/SDAM.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
This is the second in a series of PR's for implementing the retryable writes spec tests and updating our test runner framework.
This PR updates the test utils to be more usable for the new runner.
In total: 
- moves `ServerVersion` out of a client extension such that it is its own type
- adds `Comparable` conformance to `ServerVersion` so we don't need to implement/use the various `isGreaterThan`, `isLessThan`, etc. methods
- adds an initializer to `TopologyType` for use in testing
- adds an internal `sortedEquals` method to a `Document` extension for testing purposes (so we don't need to use an `expect` to get sorted equality)
- moves the `WriteModel` typealiases into `TestUtils.swift`
> SWIFT-178 Minor test utils improvements

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/CountOperation.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwift/Operations/RunCommandOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
Makes all option properties mutable. Option properties are declared with 'var' instead of 'let'.
> SWIFT-355 Make option properties mutable

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
ReadPreference getters in MongoClient, MongoCollection, and MongoDatabase should return non-optionals since their values will never be nil.
> Swift-311 Make ReadPrefrerence getters return non-optionals

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/ReadConcern.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
Part 1 of SWIFT-509: Made changes to ReadConcern so that it no longer saves a pointer to monogc type.
> Swift-509 Rewrite ReadConcern in pure Swift

- Sources/MongoSwift/BSON/AnyBSONValue.swift
Added checks for Timestamp, BSONUndefined, and DBPointer that were missing previously.
> SWIFT-508 Add check for all possible BSON values in AnyBSONValue.init(from: decoder)

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
First of many pooling PRs. Introduces a new `ConnectionString` type which `MongoClient` now uses.
> SWIFT-374 Add ConnectionString type

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
This PR introduces `Connection` and `ConnectionPool` types. `MongoClient` now stores a `ConnectionPool`.
For the moment, the `ConnectionPool` only supports single mode, and `MongoClient` continues to store a reference to the single `mongoc_client_t` so the rest of the code still works.
> SWIFT-374 Add ConnectionPool and Connection types

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/Operations/CountOperation.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/DropCollectionOperation.swift
- Sources/MongoSwift/Operations/DropDatabaseOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
- Sources/MongoSwift/Operations/RunCommandOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/MongoError+Equatable.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
[SWIFT-489](https://jira.mongodb.org/browse/SWIFT-489)
This PR adds a `codeName` field to the various `ServerError` types (`WriteError`, `WriteConcernError`, and `BulkWriteError` structs and the `.commandError` case). Additionally, I added a small test that verifies write concern errors are parsed properly, as we were missing such a test before.
This PR also reworks the internal API for getting a `MongoError`. Previously, there were two separate functions for getting an error, depending on whether you had a reply or not. Now, all errors are returned from `getMongoError`. Additionally, I refactored the private helpers a bit to be more streamlined and readable.
**Cases when codeName is not reported:**
- Until [SERVER-36755](https://jira.mongodb.org/browse/SERVER-36755) is fixed, `codeName` …
> SWIFT-489 Include codeName in server error types

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/CountOperation.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/DropCollectionOperation.swift
- Sources/MongoSwift/Operations/DropDatabaseOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
- Sources/MongoSwift/Operations/NextOperation.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/MongoSwift/Operations/RunCommandOperation.swift
This PR:
- Introduces the `OperationExecutor` protocol and a `DefaultOperationExecutor` type. `MongoClient` stores an executor which is used for executing all operations that rely on the client. 
- Updates the `Operation` protocol so that `execute` now takes in a `Connection` and `ClientSession` with which to execute an `Operation`. 
- Updates all `Operation` types to conform to the protocol 
- At the moment, they all ignore the passed-in `Connection`. In the next PR they will start using those to construct the short-lived DB and client pointers.
- The operations no longer need to store their `ClientSession`s since they get passed into `execute`.
> SWIFT-374 Operation layer changes

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/MongoNamespace.swift
- Sources/MongoSwift/Operations/CountOperation.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/DropCollectionOperation.swift
- Sources/MongoSwift/Operations/DropDatabaseOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
- Sources/MongoSwift/Operations/NextOperation.swift
- Sources/MongoSwift/Operations/RunCommandOperation.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
Apologies for the size of this, it got bigger than expected as I ended up doing a lot of refactoring in the read concern and write concern tests.
Changes:
- Added `MongoNamespace` type which DBs and collections use to track their namespaces.
- MongoDatabase and MongoCollection no longer wrap their corresponding mongoc types. They now have helper methods to create the mongoc types as needed.
- All operations now use the connections passed into `execute` to call those helpers and get the temp pointers.
- Methods returning `MongoCursor`s now check out `Connection`s and use them to call mongoc methods. The connection is then handed off to the `MongoCursor`, which will return it to the pool upon deinitialization.
- As part of the work to store a connection in the cursor, I ended up getting rid …
> SWIFT-374 MongoDatabase and MongoCollection no longer wrap libmongoc types

- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/ChangeStreamDocument.swift
- Sources/MongoSwift/ChangeStreamOptions.swift
- Sources/MongoSwift/ChangeStreamToken.swift
- Sources/MongoSwift/MongoNamespace.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ChangeStreamTests.swift
This is the first PR for [SPEC-176/ChangeStreams API](https://jira.mongodb.org/browse/SWIFT-176).
It implements:
* ChangeStream
* ChangeStreamOptions
* ChangeStreamDocument
I added some tests just for what's been added so far by calling `mongoc_collection_watch`, but these will likely change once `MongoClient.watch`, `MongoDatabase.watch`, and `MongoDatabase.watch` are implemented and just use those instead?
> SWIFT-176 Add ChangeStream, ChangeStreamDocument, and ChangeStreamOptions structs.

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/ListDatabasesOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
[SWIFT-174](https://jira.mongodb.org/browse/SWIFT-174)
This PR implements the full DB enumeration spec. As part of this change, there are now 3 methods on `MongoClient` in our public API for listing databases:
- `listDatabases -> [DatabaseSpecification]`
- `listDatabaseNames -> [String]`
- `listMongoDatabases -> [MongoDatabase]`
There were two different paths we could've chosen here:
- Implement _just_ `listDatabases` and provide an options struct for specifying `nameOnly`
- implement both `listDatabases` and `listDatabaseNames` and omit the options structs.
I opted to go with the latter for a couple reasons:
- Other drivers (e.g. Java, Go, even libmongoc) do
- It allows us to define the fields of `DatabaseSpecification` as non-optionals
- it seems more ergonomic. I imagine most users …
> SWIFT-174 Implement DB enumeration spec

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/MongoCollection+IndexTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
putting this up as a PR against the SWIFT-374 branch so I don't have to wait for SWIFT-374 to get merged to get feedback. 
This ticket was technically to make `MongoClient`, `MongoDatabase`, and `MongoCollection` threadsafe.
The only mutable state any of them had was a couple properties related to APM on `MongoClient`, which were mutable because we allow you to toggle monitoring on and off. I don't really recall why we did it this way, but it seems unnecessary to support that. I feel like generally you just want it on or you want it off and don't need to switch between the two states.
This also required us to up-front set callbacks for every single type of event as we didn't know what event types you would later decide to enable.
So rather than adding code to synchronize reading/writing …
> SWIFT-375 Make MongoClient threadsafe, and greatly simplify monitoring API

- Tests/MongoSwiftTests/ChangeStreamTests.swift
- Tests/MongoSwiftTests/SpecTestRunner/Match.swift
- Tests/MongoSwiftTests/SpecTestRunner/SpecTest.swift
This PR adds APM assertions to the change streams spec test runner. Most of the code changes actually revolve around adding support for the [MATCHES](https://github.com/mongodb/specifications/tree/master/source/change-streams/tests#spec-test-match-function) function to the runner, though.
For now, I only added logic for command started events since they're the only types of events expected here and in the other spec tests. The command monitoring tests _do_ expect other types of events, but those tests have a bunch of specific logic that I didn't think was appropriate to bring into our generic runner framework. Also, the command monitoring tests are already written, so it would just be making more work for ourselves to modify them to use a more generic system.
> SWIFT-535 Add APM assertions to change stream spec test runner

- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/Operations/NextOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/MongoCursorTests.swift
This PR implements [SWIFT-517](https://jira.mongodb.org/browse/SWIFT-517) and adds some tests around tailable and non-tailable cursor behavior.
> SWIFT-517 Return Connection to pool as soon as MongoCursor is exhausted

- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/ListIndexesOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/MongoCollection+IndexTests.swift
Implement the index enumeration spec using listIndexes and listIndexNames. Note that some aspects of the spec weren't followed for the following reasons:
-  Naming of the fields `v`, `key`, `default_language`, and `language_override`, as they conflict with the existing index management spec (https://github.com/mongodb/specifications/blob/master/source/index-management.rst#standard-api) . Instead used `version`, `keys`, `defaultLanguage`, and `languageOverride` for the respective fields.
-  Naming of the field `2dsphereIndexVersion` because of Swift constraints on naming variables with numbers.
- Optional `ns` field - the latest version of the server has omitted this field, so `testIndexOptions` couldn't depend on and test the presence of the field.
JIRA ticket: …
> SWIFT-608 Implement index enumeration spec

- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/MongoSwiftTests/DNSSeedlistTests.swift
- Tests/MongoSwiftTests/TestUtils.swift
Adds the struct `TLSConfig` to the `ClientOptions` parameter passed into `MongoClient` that allows users to specify TLS/SSL options.
JIRA ticket: https://jira.mongodb.org/browse/SWIFT-471
Design doc: https://docs.google.com/document/d/1W4DhnurX_EOBB7z8K5Ar34gBjT0Cqv607q-PZmf35uk/edit?usp=sharing
Evergreen: https://evergreen.mongodb.com/version/5d926f8f1e2d171b7b4e919b
> SWIFT-471 Client-Level TLS/SSL Options

- .evergreen/install-dependencies.sh
- .travis.yml
- README.md
- Sources/MongoSwift/BSON/Overwritable.swift
- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/WriteConcern.swift
- Tests/MongoSwiftTests/ChangeStreamTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
Bumps min libmongoc version to 1.15.1 ([SWIFT-364](https://jira.mongodb.org/browse/SWIFT-600)) and fixes various new errors introduced by the version bump and switch to having retryable reads on by default.
Also implements a bunch of quick fixes we had depending on that:
* [SWIFT-369](https://jira.mongodb.org/browse/SWIFT-369) `wtimeoutMS` is truncated if set to a value > `Int32.max`
* [SWIFT-609](https://jira.mongodb.org/browse/SWIFT-609) Enable change stream prose test that verifies no resume is attempted for specific error labels
* [SWIFT-600](https://jira.mongodb.org/browse/SWIFT-600) `Decimal128.writeToCurrentPosition` should pass a non-mutable pointer to `bson_iter_overwrite_decimal128`
> SWIFT-364, SWIFT-395, SWIFT-609, SWIFT-600 Bump mongoc version to 1.15.1

- Tests/MongoSwiftTests/ChangeStreamTests.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/DNSSeedlistTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/RetryableWritesTests.swift
- Tests/MongoSwiftTests/SpecTestRunner/SpecTestUtils.swift
- Tests/MongoSwiftTests/TestUtils.swift
I did this in the process of implementing the auth tests rather than copy-pasting the code another time... putting up in a separate PR to cut down on noise in the auth one.
I also created a new `SpecTestUtils.swift` file where this lives along with some other helpers that are only relevant in the context of spec tests.
> SWIFT-599 add helper for reading in JSON files

- .evergreen/config.yml
- .evergreen/run-atlas-tests.sh
- .evergreen/run-tests.sh
- .travis.yml
- Package.resolved
- Package.swift
- README.md
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
Drops support for Swift 4.2 and fixes various deprecation warnings that surfaced now that we are no longer using the Swift 5 compiler in 4.2 compatibility mode.
> SWIFT-632 Drop Swift 4.2 support

- .travis.yml
- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/AuthTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/Scripts/add_json_files.rb
This implements the auth JSON and prose tests as best as we can right now.
I am putting this up as a PR against the spec file helper branch for now so it can be reviewed separately. I'll switch the base branch to master once that gets merged.
FYI this fails on Travis Swift 4.2 right now. I didn't bother special-casing the call to `mongoc_uri_get_mechanism_properties` as I expect that #330 dropping 4.2 will be merged before this is.
I also made a somewhat related change to `ConnectionString` as part of this, will explain more in inline comment.
> SWIFT-429 Implement auth spec tests

- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/Operations/CountDocumentsOperation.swift
- Sources/MongoSwift/Operations/EstimatedDocumentCountOperation.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/CodecTests.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/OptionsTests.swift
- Tests/MongoSwiftTests/ReadPreferenceTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/SpecTestRunner/TestOperation.swift
- Tests/Specs/crud/tests/read/count-collation.json
- Tests/Specs/crud/tests/read/count-empty.json
- Tests/Specs/crud/tests/read/count.json
The `count()` function for `MongoCollection` has been deprecated and replaced with `countDocuments()` and `estimatedDocumentCount()`. The new API has been added, along with changes to CRUD and other tests.
JIRA ticket: https://jira.mongodb.org/browse/SWIFT-133
Evergreen: https://evergreen.mongodb.com/version/5da0c38d32f41762b94647cc
> SWIFT-133 Implement new Count API

- Examples/Docs/Sources/DocsExamples/main.swift
- README.md
This PR updates the examples and the readme to use the new API.
> SWIFT-642 Update examples to use the new BSON API

- Sources/MongoSwift/BSON/BSONDecoder.swift
This PR removes the `internalDecode` method. It was not being used, and it would be very hard to actually use this consistently across the codebase.
> SWIFT-617 Remove internalDecode

- Guides/BSON.md
This PR adds a guide overviewing basic usage of the BSON library as well as a path for migration from the old one. Because we have examples and documentation already, I decided to keep it _really_ basic. Let me know if you think it should have more meat to it or real examples.
Also, I included the migration guide here, but we could consider just putting it at the bottom of the release notes, seeing as we'll have to remove it at some point in the near future if we don't.
> SWIFT-631 Add BSON guide

- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+ChangeStreams.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/Operations/ListCollectionsOperation.swift
- Sources/MongoSwift/Operations/ListIndexesOperation.swift
- Sources/MongoSwift/Operations/NextOperation.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/MongoSwift/Operations/WatchOperation.swift
This PR does the following:
- Make `Connection` a class, which automatically checks the `mongoc_client_t` back into the pool upon `deinit`
- This enables us to remove `releaseConnection` and just ensure that any place we were calling it we now drop our reference to the `Connection` being released
- Add the override option to pass a particular `Connection` into `OperationExecutor.execute`, and use this for executing `NextOperation`s
- Remove `ConnectionStrategy`, as the combination of the previous bullet point plus the ability to simply "steal" a `Connection` via maintaining a reference to it makes the strategies obsolete
- I've also updated the `MongoCursor` init to look more like the one for `ChangeStream` and no longer take in a closure that constructs a `mongoc_cursor_t`. Once `find`, …
> SWIFT-660 Use reference counting to check in Connections

- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/MongoSwift/Operations/StartSessionOperation.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
`ClientSession` now has three possible states: `notStarted`, `started`, and `ended`. 
Per your suggestion we  will save off opTime and clusterTime if the user tries to set them before actually using the session.
I had to update the tests a bit to make sure they had `id`s available when we needed them.
> SWIFT-647 Defer creating libmongoc until first ClientSession usage in an operation

- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/Operations/AggregateOperation.swift
- Sources/MongoSwift/Operations/FindOperation.swift
- Sources/MongoSwift/Operations/ListCollectionsOperation.swift
The only operation that appears to create other operations from within it right now is `ListCollectionsOperation`.
I've updated that to directly use the new `getNextDocumentFromMongocCursor` method instead of iterating the cursor and generating new ops.
This did make me realize a problem with always caching the first document though: for situations like this, there is no way to retrieve the cached one without calling `next()`. So I added a parameter `cacheFirstDocument` to the `MongoCursor` init which defaults to false.
I also audited the driver for places we iterate cursors and only found the one in `ListCollectionsOperation` plus one in `listIndexNames` so I have fixed both of those.
I noticed that `listIndexNames` is doing a lot of unnecessary decoding work so I have opened …
> SWIFT-662, SWIFT-652: Decompose operations, and check cursor errors after iterating

- Guides/Development.md
Added the [SwiftFormat](https://github.com/nicklockwood/SwiftFormat#how-do-i-install-it) link to the development guide.
> Add SwiftFormat link to development guide

- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
Removed `autoIndexId` option from collection creation, as it has been deprecated since MongoDB 3.2.
> SWIFT-427 Remove autoIndexId option from collection creation

- .evergreen/install-dependencies.sh
fixes evergreen MacOS tasks. sample patch: https://evergreen.mongodb.com/version/5deea33561837d7951a09851
> Disable zstd when building libmongoc on evergreen

- Tests/MongoSwiftTests/SpecTestRunner/TestOperation.swift
Removed extra case for findOne in TestOperation.swift, removing the compilation warning.
> Remove findOne compilation warning in TestOperation

- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/SDAM.swift
- Sources/MongoSwiftSync/ChangeStream.swift
- Sources/MongoSwiftSync/Exports.stencil
- Sources/MongoSwiftSync/Exports.swift
- Sources/MongoSwiftSync/MongoCollection+Read.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/MongoSwiftTests/AuthTests.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCursorTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/MongoError+Equatable.swift
- Tests/MongoSwiftTests/OptionsTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/RetryableReadsTests.swift
- Tests/MongoSwiftTests/RetryableWritesTests.swift
This contains a lot of small and I think non-controversial changes I've identified we should make as part of or as a precursor to splitting up the tests.
in particular:
- moving a couple of methods that are only used in tests and are defined internally in `MongoSwift` into `TestsCommon`
- Adding a couple missing components of the sync API
- removing various unused imports to make it easier to see which files can be moved to the sync test suite with no changes
> SWIFT-667, SWIFT-342 hodgepodge of small test changes

- Tests/MongoSwiftTests/ChangeStreamTests.swift
- Tests/MongoSwiftTests/SyncTestUtils.swift
[SWIFT-644](https://jira.mongodb.org/browse/SWIFT-644)
This fixes the failing change stream tests by running `nextWithError` in a loop with a timeout, as suggested in [SPEC-1506](https://jira.mongodb.org/browse/SPEC-1506). This is necessary due to the performance regression in change streams on sharded clusters in the latest version of the server (see [SERVER-44356](https://jira.mongodb.org/browse/SERVER-44356)). Without re-polling, it is possible to miss events because the change stream hasn't received them yet, which was leading to test failures.
[evg patch](https://evergreen.mongodb.com/version/5df3f2bcc9ec4462097dfcd2)
> SWIFT-644 Fix change stream tests  failing on latest with sharded clusters

- .evergreen/config.yml
- README.md
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/MongoSwiftSyncTests/ChangeStreamTests.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
- Tests/MongoSwiftSyncTests/MongoDatabaseTests.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
No changes needed in how we install libmongoc since we depend on the r1.15 branch. This is just updating the README and deleting workarounds we had in place.
> SWIFT-689, SWIFT-539 Bump libmongoc version to 1.15.3

- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwiftSync/MongoClient.swift
- Sources/MongoSwiftSync/MongoDatabase.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/DNSSeedlistTests.swift
- Tests/MongoSwiftSyncTests/SyncAuthTests.swift
- Tests/MongoSwiftTests/ReadConcernTests.swift
- Tests/MongoSwiftTests/WriteConcernTests.swift
This PR updates `MongoSwift.MongoDatabase` to be async by using the client's new `executeOperationAsync` method, and implements `MongoSwiftSync.MongoDatabase` as a wrapper of the newly async DB.
This allowed me to reenable some tests and also required minor changes to already-enabled read/write concern tests to `wait()` on results.
> SWIFT-670 Make MongoSwift.MongoDatabase async and implement MongoSwiftSync.MongoDatabase

- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwiftSync/MongoClient.swift
- Sources/MongoSwiftSync/MongoCollection+Read.swift
- Sources/MongoSwiftSync/MongoCollection+Write.swift
- Sources/MongoSwiftSync/MongoCollection.swift
- Sources/MongoSwiftSync/MongoDatabase.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/ReadPreferenceOperationTests.swift
- Tests/MongoSwiftSyncTests/ReadWriteConcernOperationTests.swift
- Tests/MongoSwiftSyncTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftSyncTests/SyncMongoClientTests.swift
This PR makes the non-cursor read/write methods on `MongoCollection` async, and implements their synchronous equivalents.
There were a few test files that *mostly* can run but needed cursors so I enabled them and commented out the cursor portions of the files.
> SWIFT-671 Make MongoCollection read/write methods async, and implement synchronous equivalents

- .gitattributes
Adding a specially crafted line to our `.gitattributes` file will indicate that GitHub should skip certain directories when doing language statistics on the project.
> SWIFT-709 ignore vendored files for language statistics

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/MongoSwiftSync/Exports.swift
- Sources/MongoSwiftSync/MongoCollection+FindAndModify.swift
- Sources/MongoSwiftSync/MongoCollection+Indexes.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/MongoCollectionTests.swift
This PR implements non-cursor index management and find-and-modify methods on `MongoCollection`.
Per our discussion on Slack I also added a new `DropIndexesResult` type.
Unfortunately basically all of the index tests rely on `MongoCursor` being implemented (they use `listIndexes` to verify results) so I can't really enable that file without commenting out most of it yet. 
Also made some other small changes I'll explain in inline comments
> SWIFT-702 Make index management and find-and-modify methods async, implement sync versions

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/Operation.swift
Per discussion today, this PR:
* removes the `OperationExecutor` protocol
* renames `DefaultOperationExecutor` to `OperationExecutor`
* Removes the `executeOperationAsync` helper. Note that the `executeOperation` helper still exists for the sake of the API methods relying on it still compiling, but it can be deleted once we've finished up converting cursor + change stream methods to async
> Remove OperationExecutor protocol and executeOperationAsync helper 

- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwiftSync/Exports.swift
- Sources/MongoSwiftSync/MongoCollection+Indexes.swift
Removes `DropIndexesResult`. I also updated all the async docstrings for these to reflect the new behavior while I was editing them anyway.
> SWIFT-711 remove DropIndexesResult

- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/CommandMonitoringTests.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
- Tests/MongoSwiftSyncTests/ReadWriteConcernOperationTests.swift
Went through all of the test files and made sure everything has been uncommented / reenabled. 
We missed some related to indexes which I've turned on here.
Also noticed we never completed a TODO to send read preferences when specified in the command monitoring tests. It's not clear to me why they are in the tests as they don't affect the generated command events (see [here](https://github.com/mongodb/specifications/blob/master/source/command-monitoring/command-monitoring.rst#read-preference)). I guess the idea might have been to future-proof the tests if we ever did start including that kind of metadata in command events. 
The only tests not running as of this PR are the change stream ones, and @patrickfreed enables all of those in #395.
> SWIFT-710 Audit tests to ensure all are re-enabled

- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwiftSync/MongoDatabase.swift
Most of this PR is just slightly reformatting docstrings to clarify that futures fail with particular errors now, rather than the errors being thrown.
This excludes the docstrings for cursors and change streams, and methods that return cursors and change streams, as I think you started on those already, but if you think I should pick up any of that while you work on implementing those types let me know.
> SWIFT-704 Update async docstrings to reflect error propagation

- Sources/MongoSwift/SDAM.swift
[SWIFT-314](https://jira.mongodb.org/browse/SWIFT-314)
This PR updates the `ServerDescription` initializer to rely on `BSONDecoder` to decode ismaster responses instead of directly accessing the command response document.
This ticket originally sought to add graceful error handling to SDAM monitoring event construction, but without access to a logger, there really isn't anything more we can do right now. To that end, I added a number of TODO comments indicating that, once we add support for a logger, we can log when encountering errors.
> SWIFT-314 Use BSONDecoder to decode isMaster responses in SDAM monitoring

- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/MongoSwiftSync/MongoClient.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
[SWIFT-717](https://jira.mongodb.org/browse/SWIFT-717)
This PR adds a `syncClose` method to `MongoClient`. Right now, it simply ignores any errors encountered while shutting down the thread pool, but once we add logger support, we can log these errors instead. This is [the approach vapor takes](https://github.com/vapor/vapor/blob/857eb912b8bde8662e765cbec7675b10cfe924f6/Sources/Vapor/Application.swift#L108-L122).
One remaining question I have is whether we want to rename `close` and `syncClose` to `shutdown` and `syncShutdown` / `shutdownSync` to more closely match vapor's naming.
> SWIFT-717 Add syncClose method to MongoClient

- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
- Tests/MongoSwiftTests/ChangeStreamTests.swift
Due to changes introduced in [SERVER-45505](https://jira.mongodb.org/browse/SERVER-45505), this particular test case now hangs indefinitely on latest.
SPEC-1505 will introduce changes to the change streams spec to account for the new behavior.
I've opened SWIFT-722 to remind us that we should unskip this test later on.
> Skip change streams test case on 4.3+

- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/CursorCommon.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwiftSync/MongoCursor.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ChangeStreamTests.swift
- Tests/MongoSwiftTests/MongoCursorTests.swift
This adds `toArray` to async `MongoCursor` and async `ChangeStream`.
> SWIFT-718 Add a toArray method to async cursor and change stream

- Examples/Docs/Package.swift
- etc/build-examples.sh
- etc/release.sh
- etc/sed.sh
- etc/vendor-libmongoc.sh
[SWIFT-536](https://jira.mongodb.org/browse/SWIFT-536)
> SWIFT-536 Automate building examples in release script

- Sources/MongoSwift/MongoSwift.swift
- Sources/MongoSwiftSync/Exports.stencil
- Sources/MongoSwiftSync/Exports.swift
Re-exports the cleanup method so it can be called by importers of `MongoSwiftSync`.
> SWIFT-727 Re-export cleanupMongoSwift from sync API

- Examples/.swiftlint.yml
- Examples/PerfectExample/Package.swift
- Examples/PerfectExample/Sources/PerfectExample/main.swift
Updates the Perfect example to use the async API.
> SWIFT-639 Update Perfect example

- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/CursorCommon.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwiftSync/ChangeStream.swift
- Sources/MongoSwiftSync/CursorCommon.swift
- Sources/MongoSwiftSync/MongoCursor.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/MongoCursorTests.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
- Tests/MongoSwiftTests/ChangeStreamTests.swift
- Tests/MongoSwiftTests/MongoCursorTests.swift
Adds `forEach` to both types and does some internal refactoring, will explain in inline comments
> SWIFT-719 Add a forEach method to async cursors and change streams

- Examples/.swiftlint.yml
- Examples/VaporExample/Package.swift
- Examples/VaporExample/README.md
- Examples/VaporExample/Sources/VaporExample/configure.swift
- Examples/VaporExample/Sources/VaporExample/main.swift
- Examples/VaporExample/Sources/VaporExample/routes.swift
Putting up a draft PR. We probably don't want to merge this for a while because:
1) It depends on master, and not a tagged release
2) It's `@testable` importing in order to use the `all` method on `MongoCursor`
3) It's depending on a beta release of Vapor 4
4) If we do add a `syncClose` method to `MongoClient` as proposed in SWIFT-717 we'll want to use that here
> SWIFT-639 Update Vapor example

- .evergreen/config.yml
[SWIFT-690](https://jira.mongodb.org/browse/SWIFT-690)
Now that `mongo-orchestration stop` waits for the clusters to shut down, we can safely run `"upload mo artifacts"` without potentially failing. 
Unfortunately, we must run that function and `"stop mongo-orchestration"` from `post`, because if the `"run tests"` function fails, later ones defined as part of the task do not run, meaning the logs wouldn't be uploaded and the clusters wouldn't be shut down. Running in `post` causes the atlas connectivity tests to silently ignore some errors, but doing so already seems to be the standard in other drivers (e.g. [go driver](https://evergreen.mongodb.com/task_log_raw/mongo_go_driver_atlas_test_atlas_test_0d3123c45e386a6de8f2443ab0d981b685e54e56_20_02_21_16_08_33/0?type=T#L1094))
[example evg …
> SWIFT-690 Store mongod logs after evergreen runs

- README.md
Updated README to talk about both modules and add async versions of the examples.
> SWIFT-639 Update README

- Sources/MongoSwift/BSON/Document.swift
Realized these were both a bit out of date and could be worded more clearly.
Also since we don't support Swift 4 at all I just removed the `@available`.
> Fix subscript and dynamicMemberLookup docstrings

- .swiftlint.yml
- etc/install_dependencies.sh
Updates the swiftlint version used on Travis and updates the config to work with the changes made to the implicit_return rule.
> Update to swiftlint 0.39.1

- Tests/MongoSwiftTests/MongoCursorTests.swift
This PR (probably) fixes the race condition in `testTailableAwaitAsyncCursor` that occurs between the call to `next` and the subsequent call to `kill`. If the latter happens to get scheduled before the former, an error is erroneously returned. This PR adds a small waiting period between the two to give the former time to start before the `kill` is issued.
example failure: https://evergreen.mongodb.com/task_log_raw/mongo_swift_driver_tests_all__os_fully_featured~ubuntu_18.04_swift_version~5.0_ssl_auth~nossl_noauth_test_4.2_sharded_cluster_17652a3ff3bd113e136b56ec34134f45ba059a5c_20_03_06_21_41_23/0?type=T#L802
evg patch: https://evergreen.mongodb.com/version/5e6800e92fbabe51d77c1dca
> minor: fix race condition in testTailableAwaitAsyncCursor

- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Codable.swift
- Sources/MongoSwift/BSON/Document.swift
- Tests/BSONTests/BSONValueTests.swift
- Tests/LinuxMain.swift
As part of this I also made it so you can't use `Document` directly with `JSONEncoder` and `JSONDecoder`, and I updated some outdated docstrings.
> SWIFT-735 Support using ObjectId with JSONEncoder and JSONDecoder

- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/Operations/Operation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
Fixes the problem I found the other day where we can end up deadlocked if there are no connections free and all the threads in the thread pool are waiting for connections.
> SWIFT-750 Don't block in thread pool while waiting for a connection

- Sources/MongoSwift/MongoClient.swift
Remove TODOs about changing default thread pool size since we've decided to stick with 5. 
I had a comment here about justifying the default but I'm not sure it's really useful to anyone to put "we ran some benchmarks and performance peaked around there". But I added a link to my spreadsheet on the ticket so we can refer back to it if needed in the future.
> SWIFT-705 Tune NIOThreadPool size

- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Tests/MongoSwiftSyncTests/MongoCollection+BulkWriteTests.swift
[SWIFT-621](https://jira.mongodb.org/browse/SWIFT-621)
I looked through the [rest of our enums](https://mongodb.github.io/mongo-swift-driver/MongoSwift/Enums.html) (ty jazzy) and didn't see anything else that needed this treatment besides `WriteModel`.
> SWIFT-621 Provide default values for WriteModel options associated values

- Guides/TLS.md
- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
[SWIFT-434](https://jira.mongodb.org/browse/SWIFT-434)
As the ticket describes, this PR adds documentation for describing how to ensure clients are using the latest TLS protocols. As part of that,  figured it made sense to write the rest of the guide, since we didn't already have one. The guide was heavily influenced by [pymongo's guide](https://api.mongodb.com/python/current/examples/tls.html) on the same topic.
One API change that's important to note: I added a generic `tls` option to `ClientOptions`, since it seems reasonable to me that a user would want to enable TLS but not necessarily identify all the client's connecting to the database. This option is included in the URI options spec, and I think most drivers support it (pymongo does at least). cc @mbroadst
> SWIFT-434 Document how to use the driver with TLS/SSL

- Tests/MongoSwiftTests/DNSSeedlistTests.swift
This skips the initial dns seedlist discovery test that's currently failing on master.
[evg patch](https://evergreen.mongodb.com/version/5e876f0732f417510b73a85d)
> minor: skip failing DNS seedlist test

- Sources/MongoSwift/Operations/AggregateOperation.swift
- Sources/MongoSwift/Operations/FindOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/CrudV2Tests.swift
[SWIFT-772](https://jira.mongodb.org/browse/SWIFT-772)
[SPEC](https://github.com/mongodb/specifications/commit/92255e0e57027646e8ef23399d3f33fdc114221f)
Added the option `allowDiskUse` and tests that mirror the CRUDv2 tests. I figured a new file was prudent given the any tests needed here can be dropped in the future when the CRUDv2 runner is implemented.
> feat: Add allowDiskUse find option

- Sources/CLibMongoC/include/CLibMongoC_bson-config.h
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/BSON/DocumentIterator.swift
- Sources/MongoSwift/ConnectionString.swift
- etc/generated_headers/bson-config.h
This was done experimentally while investigating the C interop issue in [SWIFT-779](https://jira.mongodb.org/browse/SWIFT-779). 
The required changes ended up being pretty minimal so we should just go ahead with them now.
> SWIFT-784 Disable BSON_EXTRA_ALIGN

- Guides/Development.md
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/Operations/ListDatabasesOperation.swift
- Sources/MongoSwiftSync/Exports.swift
- Sources/MongoSwiftSync/MongoClient.swift
- Tests/MongoSwiftSyncTests/SyncMongoClientTests.swift
Added the `authorizedDatabases` option to ListDatabasesOperation as an optional param. No changes needed to the helpers.
[Check out the flag docs here](https://docs.mongodb.com/manual/reference/command/listDatabases/#dbcmd.listDatabases)
> SWIFT-773: add authorizedDatabases optional option

- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Collection.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/BSON/DocumentIterator.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/Operations/AggregateOperation.swift
- Sources/MongoSwift/Operations/CommitTransactionOperation.swift
- Sources/MongoSwift/Operations/CountDocumentsOperation.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/DropCollectionOperation.swift
- Sources/MongoSwift/Operations/DropDatabaseOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwift/Operations/EstimatedDocumentCountOperation.swift
- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
- Sources/MongoSwift/Operations/FindOperation.swift
- Sources/MongoSwift/Operations/ListCollectionsOperation.swift
- Sources/MongoSwift/Operations/ListDatabasesOperation.swift
- Sources/MongoSwift/Operations/ListIndexesOperation.swift
- Sources/MongoSwift/Operations/RunCommandOperation.swift
- Sources/MongoSwift/Operations/WatchOperation.swift
- Sources/MongoSwift/ReadPreference.swift
- Sources/MongoSwiftSync/Exports.swift
- Tests/BSONTests/DocumentTests.swift
- Tests/LinuxMain.swift
Putting this up as a draft as we should probably talk through the approach more but I figured I'd let you all talk a look.
This seems like a mostly reasonable approach to me aside from the fact that we really end up in nested closure hell in places where a libmongoc method takes in 3+ arguments.
I think there is more work to do to ensure these problems don't plague any other types. for example I think we might be vulnerable to similar issues with `ReadPreference` as it follows the same "struct backed by a private class wrapping a C type" pattern.
To summarize main changes here:
- `BSONValue` protocol's `encode` method now takes in an `inout Document` rather than a `DocumentStorage`
- `DocumentStorage` is a `private` type, and its property `_bson` is now `fileprivate`. this means both are …
> SWIFT-779 Funnel all bson_t access through helper methods

- Package.resolved
- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/ChangeStreamOptions.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/Operations/AggregateOperation.swift
- Sources/MongoSwift/Operations/CountDocumentsOperation.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Sources/MongoSwift/Operations/CreateIndexesOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Sources/MongoSwift/Operations/EstimatedDocumentCountOperation.swift
- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
- Sources/MongoSwift/Operations/FindOperation.swift
- Sources/MongoSwift/Operations/StartTransactionOperation.swift
- Sources/MongoSwift/SDAM.swift
- Sources/MongoSwift/WriteConcern.swift
- Tests/MongoSwiftSyncTests/CommandMonitoringTests.swift
- Tests/MongoSwiftSyncTests/CrudTests.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/CodableExtensions.swift
- Tests/MongoSwiftTests/ReadWriteConcernSpecTests.swift
https://jira.mongodb.org/browse/SWIFT-754
A more swifty driver with `Int` dropping the bit width specification in the user API.
> SWIFT-754: Use Int in public API as much as possible

- Package.swift
- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/AggregateOperation.swift
- Sources/MongoSwift/Operations/CountDocumentsOperation.swift
- Sources/MongoSwift/Operations/DistinctOperation.swift
- Sources/MongoSwift/Operations/EstimatedDocumentCountOperation.swift
- Sources/MongoSwift/Operations/FindOperation.swift
- Sources/MongoSwift/Operations/ListDatabasesOperation.swift
- Sources/MongoSwift/Operations/RunCommandOperation.swift
- Sources/MongoSwift/Operations/StartTransactionOperation.swift
- Sources/MongoSwift/ReadConcern.swift
- Sources/MongoSwift/ReadPreference.swift
- Sources/MongoSwift/WriteConcern.swift
- Tests/BSONTests/CodecTests.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ReadConcernTests.swift
- Tests/MongoSwiftTests/ReadPreferenceTests.swift
- Tests/MongoSwiftTests/WriteConcernTests.swift
@mbroadst I'm not sure if you want me to keep including you on these, LMK.
This PR switches `ReadPreference` over to the "create a temporary libmongoc equivalent, use it to execute a closure, and then clean it up" approach we follow for `ReadConcern`, `WriteConcern`, `MongoDatabase`, and `MongoCollection`. 
We had existing tests regarding `ReadConcern` and `WriteConcern` that verified these got set correctly on mongoc clients, dbs, and collections. I think we skipped these for `ReadPreference` at the time because it was just wrapping a `mongoc_read_prefs_t` so there was no need to test out the temporary creation of the libmongoc type.
I have now added similar tests for `ReadPreference`. As part of that I also moved libmongoc-dependent helper methods for getting the …
> SWIFT-779 Safe access to ReadPreference pointer

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/MongoSwiftSync/MongoClient.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
This PR updates our client initializer to accept an `EventLoopGroupProvider` rather than an `EventLoopGroup`.
As a result I needed to update our shutdown API since it can no longer return a future. 
I took a lot of inspiration writing shutdown code from:
- [NIOThreadPool](https://github.com/apple/swift-nio/blob/e876fb37410e0036b98b5361bb18e6854739572b/Sources/NIO/NIOThreadPool.swift#L233)
- [MultiThreadedEventLoopGroup](https://github.com/apple/swift-nio/blob/2ad77f9a9b7e4e61bd9a9639473f716e835091d9/Sources/NIO/EventLoop.swift#L834)
- [AsyncHTTPClient](https://github.com/swift-server/async-http-client/blob/master/Sources/AsyncHTTPClient/HTTPClient.swift)
Comments inline
> SWIFT-749 use ELG provider, update shutdown API

- Examples/VaporExample/Package.swift
Updates the `Package.swift` file for Vapor 4 release, which now requires `10_15` platform specification and Swift version 5.2
This built fine once the xcode project was generated.
> updates Package.swift for Vapor 4

- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/Operations/DropCollectionOperation.swift
- Sources/MongoSwift/Operations/DropIndexesOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/CrudTests.swift
- Tests/MongoSwiftSyncTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftSyncTests/MongoCollectionTests.swift
[SWIFT-204](https://jira.mongodb.org/browse/SWIFT-204)
This PR suppresses "ns not found" errors that the server returns from dropping collections and indexes on sharded clusters.
> SWIFT-204 Suppress "ns not found" errors

- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/ListDatabasesOperation.swift
- Sources/MongoSwift/Operations/StartSessionOperation.swift
- Sources/MongoSwift/Operations/WatchOperation.swift
Trying to finish up this ticket finally. This makes the `clientHandle` pointer underlying a `Connection` private, restricting access to a `withMongocConnection` method. Fortunately since we use `withMongocCollection` and `withMongocDatabase` in most places there wasn't a lot that needed to change here.
> SWIFT-779 Safe access to connection pointer

- Sources/MongoSwift/BSON/BSONValue.swift
- Tests/MongoSwiftSyncTests/SyncMongoClientTests.swift
I made the initializer and also the corresponding public property `internal`. Not clear to me if/how the property is really useful to users... I think we just use it for BSON encoding. so I'd rather keep it internal until someone needs it.
> SWIFT-826 Make Date.init(msSinceEpoch:) internal

- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/ConnectionString.swift
Guards access to `ConnectionString._uri` through a helper.
> SWIFT-779 Safe access to ConnectionString._uri

- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoError.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/TestOperationResult.swift
[SWIFT-768](https://jira.mongodb.org/browse/SWIFT-768)
This PR ensures all of our error types have a custom `localizedDescription`. This allows errors to provide a concise description of themselves that can be accessed without casting to a concrete type.
> SWIFT-768 Add custom localizedDescription to all errors

- Examples/Docs/Sources/AsyncExamples/main.swift
- Examples/Docs/Sources/SyncExamples/main.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/ReadConcern.swift
- Sources/MongoSwift/WriteConcern.swift
- Sources/MongoSwiftSync/ClientSession.swift
- Sources/MongoSwiftSync/MongoClient.swift
- Sources/MongoSwiftSync/MongoDatabase.swift
- Tests/BSONTests/CodecTests.swift
- Tests/MongoSwiftSyncTests/ClientSessionTests.swift
- Tests/MongoSwiftSyncTests/MongoCollectionTests.swift
- Tests/MongoSwiftSyncTests/MongoDatabaseTests.swift
- Tests/MongoSwiftSyncTests/ReadWriteConcernOperationTests.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/CodableExtensions.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/SpecTest.swift
- Tests/MongoSwiftTests/ReadConcernTests.swift
- Tests/MongoSwiftTests/WriteConcernTests.swift
Added convenience properties to ReadConcern and WriteConcern.
Some notes:
- ReadConcern no longer has a public constructor, users can rely on the static other method to make unsupported ReadConcerns.
- WriteConcern now has a `fileprivate init` this was done because we needed a non-throwing constructor to add the `static let majority: WriteConcern` property.
- We now make use the convenience API internally so the changes are being tested.
> SWIFT-815: More convenient API for ReadConcern/WriteConcern creation

- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/Operations/CountDocumentsOperation.swift
- Sources/MongoSwift/SDAM.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/MongoSwiftSyncTests/RetryableReadsTests.swift
- Tests/MongoSwiftSyncTests/RetryableWritesTests.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/FailPoint.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/SpecTest.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/TestOperations/TestOperation.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/TestOperations/TestOperationResult.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/TestOperations/TestRunnerOperations.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftSyncTests/TransactionsTests.swift
[SWIFT-774](https://jira.mongodb.org/browse/SWIFT-774)
This PR adds support in the spec test runner for sharded transactions tests. It also refactors the runner to make skipping tests a little easier, repurposes the `FailPointConfigured` protocol to be more generally useful (it's now a requirement of the `SpecTest` protocol), and splits up `TestOperation.swift` into a subdirectory of different operations for easier code discovery.
The changes to `FailPointConfigured` will close out [SWIFT-755](https://jira.mongodb.org/browse/SWIFT-755) as part of this work.
> SWIFT-774 Implement sharded transactions tests

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/Credential.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCredential.swift
- Sources/MongoSwiftSync/Exports.swift
- Tests/MongoSwiftSyncTests/SyncAuthTests.swift
- Tests/MongoSwiftTests/AuthTests.swift
I made the Credential struct public so we can share the data structure with users specifying their authentication options. Since the URI in libmongoc is the source of truth about what settings the user wishes to have when connecting to mongo I set up a function to set all the authentication properties in the URI from the user specified Credential. Added tests to cover.
> SWIFT-640: Add authentication options to ClientOptions

- Sources/MongoSwift/ConnectionPool.swift
I discovered yesterday that if you created a `MongoClient` with invalid `maxPoolSize` we would leak the `mongoc_client_pool_t`. This fixes that issue.
> Avoid ConnectionPool leak in case of invalid options

- Examples/Docs/Sources/AsyncExamples/main.swift
- Examples/Docs/Sources/SyncExamples/main.swift
[SWIFT-423](https://jira.mongodb.org/browse/SWIFT-423)
This PR adds the examples to be rendered in the official MongoDB [docs page](https://docs.mongodb.com/manual/core/transactions-in-applications/) on transactions usage in drivers.
> SWIFT-423 Add transactions examples for docs

- Sources/MongoSwift/BSON/BSON.swift
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
- Sources/MongoSwift/Operations/ListDatabasesOperation.swift
- Tests/BSONTests/BSONValueTests.swift
- Tests/BSONTests/Document+SequenceTests.swift
- Tests/BSONTests/DocumentTests.swift
- Tests/MongoSwiftSyncTests/CommandMonitoringTests.swift
- Tests/MongoSwiftSyncTests/CrudTests.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
- Tests/MongoSwiftSyncTests/MongoCollectionTests.swift
- Tests/MongoSwiftSyncTests/MongoCursorTests.swift
- Tests/MongoSwiftSyncTests/MongoDatabaseTests.swift
- Tests/MongoSwiftSyncTests/ReadPreferenceOperationTests.swift
- Tests/MongoSwiftSyncTests/ReadWriteConcernOperationTests.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/FailPoint.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/Match.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftTests/ReadWriteConcernSpecTests.swift
Renames all public and internal methods of the form `asX` to `toX`.
Relatedly I remembered while doing this that we had decided in the BSON design doc we would switch to using `toX` methods for BSON interop with other types, rather than adding initializers to types we don't own. But I forgot to add that to the list Neal did in #477. I went ahead and moved the `BSONBinary` -> `UUID` logic into `BSONBinary.toUUID`, and the `BSONRegularExpression` -> `NSRegularExpression` logic into `BSONRegularExpression.toNSRegularExpression`.
> SWIFT-835 Standardize on conversion method names

- Sources/MongoSwift/WriteConcern.swift
- Tests/MongoSwiftTests/ReadWriteConcernSpecTests.swift
- Tests/MongoSwiftTests/WriteConcernTests.swift
Renames this case to be more in line with what we're calling it in MongoDB docs now.
> SWIFT-863 Rename WriteConcern tag case to custom

- Guides/Transactions.md
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/Operations/StartSessionOperation.swift
- Sources/MongoSwiftSync/ClientSession.swift
[SWIFT-776](https://jira.mongodb.org/browse/SWIFT-776)
This PR adds examples of retrying transactions to the transactions guide. It does so by simply linking to the official docs, since those examples are quite thorough (and will contain the Swift examples written in #478 ).
This PR also adds clarification in the documentation about how options (e.g. write concern) are propagated in transactions. This is based off of feedback from the [latest jepsen analysis](http://jepsen.io/analyses/mongodb-4.2.6) of MongoDB's transactions.
> SWIFT-776 Add transaction retry examples

- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+ChangeStreams.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwiftSync/ChangeStream.swift
- Sources/MongoSwiftSync/MongoCursor.swift
[SWIFT-853](https://jira.mongodb.org/browse/SWIFT-853)
> SWIFT-853 Clarify requirements for when when cursors/change streams need to be killed

- Sources/CLibMongoC/include/CLibMongoC_mongoc-uri.h
- Sources/CLibMongoC/mongoc/mongoc-client.c
- Sources/CLibMongoC/mongoc/mongoc-topology.c
- Sources/CLibMongoC/mongoc/mongoc-uri.c
- etc/CDRIVER-3532-directConnection.diff
- etc/CDRIVER-3623-fix-setting-apm-in-pooled-client.diff
- etc/vendor-libmongoc.sh
This PR updates our vendoring script to apply two patches to CLibMongoC, and also brings in the results of running the updated script.
successful patch: https://evergreen.mongodb.com/version/5ecd7264306615532c0d77cb
and libmongoc patch confirming that all their tests pass with 1.16 + these patches applied: https://evergreen.mongodb.com/version/5ecdaf2132f417195909fc40 (@kevinAlbs says it safe to ignore the debian-package-build and rpm-package-build failures)
Work to give us the new behavior (unspecified directConnection is treated as if it's set to false) will come in a follow-up PR.
> Patch in necessary libmongoc fixes for 1.0

- Package.swift
- README.md
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/CodingStrategies.swift
- Tests/BSONTests/DocumentTests.swift
This adds a minimum macOS version to our package manifest, and clarifies supported / tested platforms in our README.
This also lets us remove the availability checks for 10.12+ we had to use for the date formatter.
> SWIFT-855 Add minimum macOS version and document OS support policy

- Examples/Docs/Sources/AsyncExamples/main.swift
- Sources/MongoSwift/ChangeStreamOptions.swift
- Sources/MongoSwiftSync/Exports.swift
https://jira.mongodb.org/browse/SWIFT-827
`CollectionType` is out of scope (we discussed that since it's an administrative api we can leave it as is)
That only leaves `FullDocument` which is now a RawRepresentable struct with a public static other function
> SWIFT-827: Rewrite enums with ".other" case as structs

- Sources/MongoSwift/BSON/BSON.swift
- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONDocument.swift
- Sources/MongoSwift/BSON/BSONDocumentIterator.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Overwritable.swift
- Tests/BSONTests/BSONCorpusTests.swift
- Tests/BSONTests/BSONValueTests.swift
- Tests/BSONTests/CodecTests.swift
- Tests/BSONTests/Document+SequenceTests.swift
- Tests/BSONTests/DocumentTests.swift
- Tests/LinuxMain.swift
All changes listed in ticket:
https://jira.mongodb.org/browse/SWIFT-858
Additionally changed:
- `BSONType` is `UInt8` instead of UInt32
> SWIFT-858: Duplicate pure Swift BSON breaking changes in driver

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/BSONTests/DocumentTests.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftSyncTests/SDAMTests.swift
- Tests/Specs/initial-dns-seedlist-discovery/tests/direct-connection-false.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/direct-connection-true.json
This builds on my previous PR to add libmongoc support for `directConnection=true` to give us the desired discover behavior by default.
You can view a summary of the spec changes [here](https://github.com/mongodb/specifications/commit/e56f5eceed7729f8b9b43a4a1f76c7e5840db49f).
I was able to pull in the relevant initial DNS seedlist discovery tests as we implement that test runner, but the other tests use the SDAM and connection string test runners which we do not implement yet.
I did some manual local testing using SDAM monitoring and everything seems to work as expected in terms of initial topology assumptions as well as errors being reported in the right scenarios.
> SWIFT-742 Implement unified replica set discovery behavior

- Sources/MongoSwift/BSON/BSONDocument.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/BSONTests/BSONCorpusTests.swift
- Tests/BSONTests/CodecTests.swift
[SWIFT-882](https://jira.mongodb.org/browse/SWIFT-882)
This PR converts the extJSON computed properties to methods, since they may be computationally expensive. @mbroadst noted that they would be superseded by `ExtendedJSONEncoder`, and that we would probably deprecate them once that was introduced. Since these produce `String`s, they could perhaps be useful as conveniences over invoking the encoder, so I also added "String" as a suffix to their method names.
These changes are not release blockers, but if we do want to make them we need to do so today, so I just put up the PR now to get the discussion rolling.
> SWIFT-882 Convert extJSON properties to methods

- Sources/MongoSwift/Operations/FindOperation.swift
[SWIFT-869](https://jira.mongodb.org/browse/SWIFT-869)
> SWIFT-869 allowDiskUse option for find should be documented as only being supported in 4.4+

- Examples/Docs/Sources/AsyncExamples/main.swift
- Examples/Docs/Sources/SyncExamples/main.swift
- Examples/KituraExample/Package.swift
- Examples/PerfectExample/Package.swift
- Examples/VaporExample/Package.swift
- Guides/BSON.md
- Guides/Change-Streams.md
- Guides/TLS.md
- README.md
Updates guides and examples to use API changes.
The BSON one has the biggest diff. I tried actually running all the examples and I'm not sure some of them ever compiled to begin with... whoops. So all that is fixed.
I'll hold off on merging until a little while before I tag the release to avoid having non-updated info out in the wild.
> Update guides, examples, and README for 1.0

- Sources/MongoSwift/ConnectionString.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
Implements the URI options spec tests: https://github.com/mongodb/specifications/blob/master/source/uri-options/tests/README.rst
> SWIFT-573 Implement URI options spec test runner

- Sources/MongoSwift/ConnectionString.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SDAMTests.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
(You should review SWIFT-573 first)
This contains additions to the URI options test runner to support running the connection string spec tests as well.
> SWIFT-885 Implement connection string spec tests

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
Adds the appName option. I tested this works by adding an app name in a test and looking at the mongod log to see if it shows up.
> SWIFT-897 Add appName option to MongoClientOptions

- .swiftlint.yml
`swiftlint autocorrect` now ignores `MongoSwiftVersion.swift`
> minor: ignore MongoSwiftVersion.swift in swiftlint

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
This adds support for the replica set option and tests for it. Writing the tests made me realize I should probably at least add a simple test about options precedence for appName so I went ahead and added that too.
> SWIFT-898 Add replicaSet option, and tests for replicaSet + appName options

- .swiftformat
- .swiftlint.yml
- .travis.yml
- etc/install_dependencies.sh
The SwiftFormat version we're using is a bit out of date, so we're seeing discrepancies between what travis formats and our local formatters in #503. To fix that, I bumped SwiftFormat to its latest version. As part of this, I also made SwiftFormat ignore any `.build` directories in any subfolder of the driver (e.g. including `Examples`). Also, I moved the installation stuff into `etc` so that we don't have to specifically skip each tool we install as part of the formatting process.
> minor: bump SwiftFormat version to 0.44.16

- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/MongoSwiftTests/DNSSeedlistTests.swift
This consolidates all of our options settings for clients into a single place, making it easier to reason about and laying the groundwork for doing our own validation of options in a future PR (see [SWIFT-929](https://jira.mongodb.org/browse/SWIFT-929)).
Previously, we set TLS options and the pool size option directly on the pool rather than on the `mongoc_uri_t`.
> SWIFT-928 Consolidate setting of client options

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
Adds support for specifying localThresholdMS via client options.
We can't really test this now beyond confirming its set correctly on the URI/overridden correctly. Once we eventually implement server selection tests, it will be tested more thoroughly there.
> SWIFT-906 Add localThresholdMS option

- Sources/MongoSwift/ConnectionString.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
Throw an error if users provide this option, due to problematic libmongoc implementation. It feels a little weird to throw on this option but not any other unsupported options, but I don't really know what else we can do.
> SWIFT-912 Error if minPoolSize is specified

- Sources/MongoSwift/Compressor.swift
- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwiftSync/Exports.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
This ended up having some API-related concerns so adding @mbroadst as well.
This adds support for specifying compressors (currently only zlib is supported), as well as an optional level to use for zlib compression, via `MongoClientOptions`.
> SWIFT-903, SWIFT-909: Add compression options to MongoClientOptions

- Sources/MongoSwift/ConnectionString.swift
This refactors the `ConnectionString` type to split up logic into a number of methods roughly corresponding to different specs. This should make it easier to introduce validation logic for a few options / options combos in the next PR.
While I was at it I also introduced some helpers to make setting various options and throwing errors less repetitive, and to take advantage of libmongoc's constants for URI options as much as possible. I figure we will be able to easily swap in our own constants for those later on.
> SWIFT-929 Refactor ConnectionString option setting and validation into sub-methods

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/ReadPreference.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
This PR does the following: 
1. Added `tlsInsecure` option to client options.
2. Adds validation for various combinations of options / usages of options that are invalid, as specified in the URI options spec (see [this section](https://github.com/mongodb/specifications/blob/master/source/uri-options/uri-options.rst#conflicting-tls-options) and the two following it.) When these situations are present in the initial string, libmongoc handles validating them for us, but when we override any of the involved options after the `mongoc_uri_t` is created we do not necessarily get validation. See [CDRIVER-3723](https://jira.mongodb.org/browse/CDRIVER-3723) for details.
3. I also realized that the "lack of libmongoc errors on invalid timeouts in the input string" issue (mentioned in …
> SWIFT-901, SWIFT-929 Add tlsInsecure option, validate options

- Package.swift
- Sources/CLibMongoC/include/CLibMongoC_bson-config.h
- Sources/CLibMongoC/include/CLibMongoC_bson-prelude.h
- Sources/CLibMongoC/include/CLibMongoC_bson-version.h
- Sources/CLibMongoC/include/CLibMongoC_common-prelude.h
- Sources/CLibMongoC/include/CLibMongoC_mongoc-config.h
- Sources/CLibMongoC/include/CLibMongoC_mongoc-prelude.h
- Sources/CLibMongoC/include/CLibMongoC_mongoc-version.h
- etc/generated_headers/bson-config.h
- etc/generated_headers/bson-version.h
- etc/generated_headers/mongoc-config.h
- etc/generated_headers/mongoc-version.h
- etc/vendor-libmongoc.sh
XCode seems to have difficulty transferring SwiftPM conditional defines to generated XCode projects. This patch removes the need to depend on these definitions by hardcoding the changes directly in the source.
**NOTE:** I don't know if this fully solves the issue as we still need to convey linker flags
> SWIFT-952 Remove dependency on conditional defines in package file

- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/ChangeStreamEvent.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/WatchOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
This PR works around the fact that invalid events do not have associated namespaces by accepting a `MongoNamespace` in `ChangeStream.init`, and then storing that namespace under `ns` in the `ChangeStream'`s `BSONDecoder'`s `userInfo`.
`ChangeStreamEvent` then looks for the matching key when decoding, and falls back to it if there is no key present in the original document.
Per conversation in driver-devs it appears that as of now anyway it's impossible to encounter an invalidate event on a client.
> SWIFT-957 Fill in namespace on invalidate events

- .travis.yml
- Sources/MongoSwift/CursorCommon.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Sources/TestsCommon/ServerVersion.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/MongoCursorTests.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftTests/MongoCursorTests.swift
SWIFT-958
This fixes a bug where cursors would iterate forever after encountering a non-`DecodingError` by ensuring `next` returns `nil` once after the error. This does not apply to `tryNext` or `toArray`, since those are `throws`. Also, in the case of `tryNext`, `nil` doesn't necessarily imply that the cursor is dead.
> SWIFT-958 Ensure nil is returned from next() before ClosedCursorError

- Sources/MongoSwift/MongoCollection+Read.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/MongoCollectionTests.swift
SWIFT-974
This PR fixes a bug in `Collection.findOne` where the cursor would get leaked if a `DecodingError` occurred while decoding the result.
> SWIFT-974 Fix leak in Collection.findOne when encountering DecodingError

- Package.resolved
- Package.swift
- Sources/MongoSwift/BSON/BSONPointerUtils.swift
- Sources/MongoSwift/ClientSession.swift
- Tests/BSONTests/BSONPointerUtilsTests.swift
- Tests/BSONTests/DocumentTests.swift
- Tests/LinuxMain.swift
SWIFT-961
This PR adds [`swift-bson`](https://github.com/mongodb/swift-bson) as a dependency to the driver and adds some extensions to allow interop with libbson's `bson_t`.
> SWIFT-961 Add withBSONPointer to new BSONDocument

- .evergreen/config.yml
- Sources/MongoSwift/CursorCommon.swift
- Sources/MongoSwift/Operations/StartSessionOperation.swift
While it seems like macOS testing may be blocked for a while, we can go ahead and add 5.3 testing on Linux now.
Evergreen patch in progress (added some 5.1 and 5.2 tests since I bumped the patch versions on those):
https://spruce.mongodb.com/version/5f6d04e9d1fe0779e9e01612/tasks
> SWIFT-1010 Test 5.3 on Ubuntu variants

- Sources/MongoSwift/APM.swift
- Tests/MongoSwiftSyncTests/SDAMTests.swift
This is a longstanding inefficiency in the driver, but only came up as a problem when using the new BSON library.
Even if the user has no handlers registered, we create a corresponding Swift event, which in the case of e.g. a command started event for a large command is quite expensive (especially now that - at least for the moment - by default we validate incoming documents.)
This PR amends that by introducing a new concept of a monitoring "component" for each event type. Depending on the component of the event to be published, we inspect the client to see if any corresponding handlers exist.
I am feeling like this file is getting a little wild, using a lot of different types and protocols, but at the same time I couldn't figure out a clean way to accomplish this without the addition of …
> SWIFT-1015 Only create monitoring events if they are being consumed

- .evergreen/config.yml
- .evergreen/run-tests.sh
- .swiftlint.yml
- etc/convert-test-results.swift
Putting this up as I'm calling it finished, but no pressure to review it during Skunkworks.
This adds a script written in Swift which reads input (which should be `swift test` output) from stdin, parses it into data structures, converts those structures to XML, and then writes the resulting XML to stdout.
This script is now used when running our tests on Evergreen to upload the results. 
With a small modification (updating list of suite names to skip) this should be reusable for the BSON repo.
> SWIFT-400 Improve Evergreen test result output

- Sources/TestsCommon/CommonTestUtils.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
For readability purposes, trying to break this PR up into separate chunks when I can.
This PR introduces changes to our `TestRequirement` and `TestTopologyConfiguration` types to support usage with the new unified test format.
> SWIFT-913 Make required changes to TestRequirement type for unified runner

- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/SchemaVersion.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestFile.swift
- Tests/MongoSwiftSyncTests/UnifiedTests.swift
Adds some new data structures to represent the contents of unified test files. For now I have left some of the sub-contents which will require their own Codable types as `BSONDocument`s; these will switch to using more specific types in future PRs.
> SWIFT-913 Add data structures for unified test schema version, test file, and test

- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/CodableExtensions.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/EntityDescription.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/ExpectedEventsForClient.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestFile.swift
- Tests/MongoSwiftSyncTests/UnifiedTests.swift
Adding some more data structures and support for (at least some types) for verifying only expected options are present. I'll add some commentary inline.
> SWIFT-913 Add EntityDescription and ExpectedEventsForClient types for unified test runner

- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
We started getting some failures against latest due to [SERVER-47081](https://jira.mongodb.org/browse/SERVER-47081) being merged in yesterday.
> Stop testing bucketSize index option on 4.9+

- .evergreen/config.yml
- .evergreen/install-swift.sh
- .evergreen/install-tools.sh
- .swiftformat
- .swiftlint.yml
- .travis.yml
My branch name was a bit premature as code coverage is still being generated through Travis, but this moves everything else over and stops running tests on Travis altogether. 
It would be good to move code coverage too, though I think that will be a bit more complicated so I've opened another ticket to handle that separately at a later time: SWIFT-1019. The coverage isn't very accurate at this point because it only tests against a standalone on 3.6. We should be generating a number of reports across different Evergreen runs and merging them together. I don't think we really rely much on code coverage feedback in PRs anyway so it seems less essential to get timely feedback on.
Sample successful patch: https://spruce.mongodb.com/version/5faf1bc09ccd4e21e67cd68d/tasks
Sample patch where I …
> SWIFT-592 Move format/lint/sourcery check to Evergreen

- Sources/MongoSwift/Operations/AggregateOperation.swift
- Sources/TestsCommon/SpecTestUtils.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/TestOperations/CollectionOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/HasListableProperties.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/SpecialTestOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/TestWriteModel.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedChangeStreamOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedClientOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedCollectionOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedDatabaseOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedOperation.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedSessionOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTests.swift
This PR is a bit larger than the past ones, but is for the most part very repetitive so hopefully is not too difficult to review. 
I'm sure we are missing some operations right now, and/or optional arguments for operations, that might be added at some point as I did not exhaustively comb through every spec, but the design of the runner here where we error on both unsupported operation names and unsupported argument names should make it very easy to identify those cases in the future.
Comments inline
> SWIFT-913 Support for remaining test operations

- Sources/TestsCommon/APMUtils.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/EntityDescription.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
- Tests/MongoSwiftSyncTests/UnifiedTests.swift
This adds support for all of the setup code that is necessary to run before executing operations, e.g. populating entity map, running necessary commands to ensure the topology is in a good state, etc.
> SWIFT-913 Add support for test runner and test case setup

- Sources/MongoSwift/MongoCollection+Indexes.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
Adds support for hidden indexes. [JIRA](https://jira.mongodb.org/browse/SWIFT-828)
> SWIFT-828 Add support for hidden indexes

- Sources/MongoSwift/MongoCollection+Write.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/EntityDescription.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/Matching.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedChangeStreamOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedCollectionOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedOperation.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
- Tests/MongoSwiftSyncTests/UnifiedTests.swift
This adds support for everything that is needed to execute the [first test in the first file](https://github.com/mongodb/mongo-swift-driver/blob/8bd6f978d56a69a54dfb4c9ce74d8b8fdd78d828/Tests/Specs/unified-test-format/tests/valid-pass/poc-change-streams.json#L92) and perform the required assertions on the result:
- Extends `UnifiedOperationProtocol` to add an `execute` method and adds a general `executeAndCheckResult` method to `UnifiedOperation`
- Implements the `execute` method for operations used in this test (`createChangeStream`, `insertOne`, `iterateUntilDocumentOrError`)
- Matching (non-error) results
- Saving results as entities
- Matching observed events
The code is temporarily modified, for now, to only execute that test.... I could have kept going but I wanted to get your …
> SWIFT-913 Start adding support for operations; support non-error result and event matching

- Tests/MongoSwiftSyncTests/UnifiedTestRunner/Context.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/Matching.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedOperation.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
This introduces a simple Context object (which currently just contains a path, but could have more stuff on it later if we want) which gets passed around throughout all of the matching assertions and is used to construct error messages on failure.
Rather than returning context objects from the matching methods, it seemed simpler to convert all of them to throw errors in-place when something doesn't match, rather than just indicating it with a boolean.
Some sample output (which I got by messing around with the expectations in the first change stream tests JSON to make them fail intentionally):
```
[MongoSwiftSyncTests.UnifiedRunnerTests testSampleUnifiedTests] : failed: caught error: "NonMatchingError(expected: "MongoSwift.BSON.int32(2)", actual: …
```
> SWIFT-913 Add context passing in tests

- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/ChangeStreamOptions.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
Makes `startAfter` public now that libmongoc 4.2 change streams has been released.
> SWIFT-519 Make startAfter public

- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/FailPoint.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/Context.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/EntityDescription.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/Matching.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/SpecialTestOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedChangeStreamOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedClientOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedCollectionOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedDatabaseOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedOperation.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedSessionOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
- Tests/MongoSwiftSyncTests/UnifiedTests.swift
As I mentioned in the team channel there seem to be some sporadic failures on evg along the lines of the transactions tests ones we've been seeing lately. I'm going to investigate that now but I don't think it needs to block starting review on this.
Sorry that this is a bit larger than past PRs, but a lot of it is just operation execution boilerplate so hopefully should be easy to review.
> SWIFT-913 Implement support for remaining operations and error matching

- Sources/MongoSwift/EventLoopBoundMongoClient.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/CreateCollectionOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/EventLoopBoundMongoClientTests.swift
- mongo-swift-driver.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Adds a method `EventLoopBoundMongoClient.db` that returns a bound `MongoDatabase`.
- Updates `MongoDatabase.collection` to return a bound `MongoCollection`.
- Updates the calls to `operationExecutor` to pass in the `EventLoop` (except for the ones where `MongoCursor` and `ChangeStreams` are returned, those will be modified in the next PR).
- Adds tests to verify that the futures returned by the methods are on the bound event loop.
> SWIFT-1029 Add support for EventLoop binding for MongoDatabase and MongoCollection

- Sources/MongoSwift/BSON/BSONPointerUtils.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
SWIFT-1072
This PR contains the driver-side changes of SWIFT-1072. This also is the only change required for the find performance improvements as well, making this the last PR of SWIFT-993.
Benchmark results (insertion ones copied from PR on `swift-bson`):
| benchmark                       | libbson based median time | target time (1.25x) | unoptimized swift-bson | post-optimizations |
|---------------------------------|---------------------------|---------------------|------------------------|--------------------|
| small doc bulk insert           | 0.096                     | 0.12                | 4258.673               | 0.117              |
| large doc bulk insert           | 0.332                     | 0.415               | 59.637                 | 0.454              |
| small doc …
> SWIFT-1072 Improve result parsing performance

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
SWIFT-1045
The `MongoClient` initializer currently performs a blocking DNS request. In the event of a DNS outage, this could block an event loop indefinitely. This PR updates the `MongoClient` initializer to construct the `mongoc_client_pool_t` on the thread pool instead, ensuring the initializer does not block.
I tested this by configuring an invalid DNS server and trying to create a client. After the changes it still happens immediately, prior to the changes it hangs until a backup DNS server is tried (~10s).
> SWIFT-1045 Ensure MongoClient initializer does not perform blocking DNS request

- Package.resolved
- Sources/TestsCommon/CommonTestUtils.swift
> SWIFT-1086 Update sortedEquals impl to use equalsIgnoreKeyOrder

- Sources/TestsCommon/CommonTestUtils.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/SpecTest.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
Fixes the transactions test failures by using separate clients for running specific commands against each mongos. As discussed in #driver-devs, this accounts for cases where the setup client has not yet reconnected to one of the mongoses after a test.
I thought about porting this over to the unified runner, but that one is fairly specific that the internal client should be used for terminating open transactions and doesn't appear to be suffering from this issue on its own. It may become necessary in the future if any similarly racy tests start using that runner.
Evg patch against all sharded variants (realized those < 4.2 were useless too late): https://evergreen.mongodb.com/version/601c817c850e612ab835c3c9
no macOS results in yet but as you can see this has fixed all the Ubuntu failures …
> Fix txn tests

- etc/docs-main.md
- etc/generate-docs.sh
- etc/release.sh
- etc/update-index.py
SWIFT-734
This PR updates the release and documentation scripts to generate the docs in a way that works for multiple versions of the driver, based on [SwiftNIO's setup](https://github.com/apple/swift-nio/tree/gh-pages). See #600 for the changes it makes to the `gh-pages` branch (or rather, [check out the branch of my fork](https://github.com/patrickfreed/mongo-swift-driver/tree/SWIFT-734/gh-pages-update), since that diff is crazy).
> SWIFT-734 Update scripts to maintain multiple versions of the documentation

- Examples/ComplexVaporExample/README.md
- Examples/Docs/Package.swift
- Guides/BSON-Guide.md
- Guides/Development.md
- Guides/Multithreaded-Usage.md
- Package.resolved
- Package.swift
- README.md
- Sources/MongoSwift/ChangeStreamOptions.swift
- Sources/MongoSwift/ReadConcern.swift
- etc/build-examples.sh
SWIFT-992
In preparation for renaming the default branch of this repository from `master` to `main`, this PR updates any existing references to the `master` branch accordingly.
> SWIFT-992 Update references to master branch

- .evergreen/config.yml
- .evergreen/install-dependencies.sh
- .evergreen/run-tests.sh
- .swiftlint.yml
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
- etc/convert-test-results.swift
SWIFT-1061
This PR makes the following changes to the r1.0 branch to support continuous matrix testing:
- Backport the xunit test results parser for pretty test output (considered a SHOULD in the matrix project)
- Allow optional installation of dependencies in `run-tests.sh` via the `INSTALL_DEPS` variable
- Introduce a workaround to `install-dependencies.sh` to avoid a clash between matrix testsing's `$PLATFORM` and [the `$PLATFORM` used in swiftenv](https://github.com/mbroadst/swiftenv/blob/osx-install-path/libexec/swiftenv-install#L44)
- complete SWIFT-763 to fix failing test on latest (will need to be "forward"-ported to `main` as well)
Example matrix patch: https://spruce.mongodb.com/version/60246becd6d80a75c95f89f1/tasks
Example r1.0 patch: …
> SWIFT-1061 Update r1.0 branch to support matrix testing

- README.md
> SWIFT-1034 Add sorted find example to README

- .jazzy.yml
- etc/docs-main.md
- etc/generate-docs.sh
- etc/get_bson_version.py
This prepares us for the 1.1.0 release where the BSON symbols are no longer available. You can try this out locally with the docs generation script.
> SWIFT-1113 Include BSON symbols in driver docs

- Sources/CLibMongoC/include/CLibMongoC_bson-version.h
- Sources/CLibMongoC/include/CLibMongoC_mongoc-version.h
- Sources/MongoSwift/MongoSwift.swift
- etc/generated_headers/bson-version.h
- etc/generated_headers/mongoc-version.h
You can't really test this besides trying it out. I did so by adding `addWrappingLibraryMetadata(name: "blah", version: "x.y.z")` to the start of a test case and then only running that and looking at the mongod log. It contains:
```js
{"t":{"$date":"2021-02-18T18:17:22.206-05:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn43","msg":"client metadata","attr":{"remote":"127.0.0.1:64189","client":"conn43","doc":{"driver":{"name":"mongoc / MongoSwift / blah","version":"1.17.4 / 1.0.0 / x.y.z"},"os":{"type":"Darwin","name":"macOS","version":"20.2.0","architecture":"x86_64"},"platform":"(null)cfg=0x0001d62245 posix=200112 stdc=201112 CC=clang 12.0.0 (clang-1200.0.32.29) CFLAGS=\"\" LDFLAGS=\"\""}}}
```
> SWIFT-985 Add client metadata support for wrapping libraries

- .evergreen/config.yml
- .evergreen/run-ocsp-test.sh
- .evergreen/run-tests.sh
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
SWIFT-888
This PR adds tests for OCSP support to the evergreen matrix as required in the specification. Note, due to CDRIVER-3759, the "soft fail" test may occasionally fail on macOS. I filed DRIVERS-1574 to cover the work for fixing that.
This PR does not introduce any new functionality to the driver, nor does it test the options parsing behavior. That will be completed in a subsequent PR for SWIFT-787.
patch with OCSP tests: https://evergreen.mongodb.com/version/60303e863627e04ae9e0061d
There are a few failures on Ubuntu 18.04 + latest, and they seem to be consistent with libmongoc's [OCSP testing](https://evergreen.mongodb.com/build/mongo_c_driver_r1.17_ocsp_264fc940df5a2d86d83c51b9523073a5d007a55f_21_02_02_16_10_14). I asked in `#driver-devs` to see if anyone else is experiencing …
> SWIFT-888 OCSP support testing

- Guides/TLS-Guide.md
- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SyncMongoClientTests.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
SWIFT-787
This PR adds OCSP configuration options to `MongoClientOptions` and enables the associated tests. It also adds some one-off prose tests as mentioned in the specification and updates the TLS guide to describe them.
> SWIFT-787 Add OCSP configuration options

- .evergreen/config.yml
- .evergreen/install-tools.sh
- Sources/MongoSwiftSync/Exports.swift
- Tests/LinuxMain.swift
Updates us to the latest version of Sourcery, and removes the need for us all to be on the same exact version of Sourcery going forward by ignoring any lines starting with a "/" when checking the diff.
Here's a sample patch with my first commit only, where I updated the version being used on Evergreen but did not actually regenerate the files using that version string: https://spruce.mongodb.com/version/605255a61e2d171f05624717
> Bump sourcery version, and ignore comments when checking Sourcery diffs going forward

- Sources/MongoSwift/ChangeStreamEvent.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
- Tests/MongoSwiftTests/ChangeStreamTests.swift
- Tests/Specs/change-streams/tests/legacy/change-streams-errors.json
- Tests/Specs/change-streams/tests/legacy/change-streams-resume-errorLabels.json
- Tests/Specs/change-streams/tests/legacy/change-streams-resume-whitelist.json
- Tests/Specs/change-streams/tests/legacy/change-streams.json
- Tests/Specs/change-streams/tests/unified/change-streams.json
This PR is a hodgepodge of changes I'll attempt to explain the thread between here...
Sorry for the large diff, it's mostly due to syncing JSON spec test files; you do not need to review those.
The main purpose of this ticket was to add a new property `truncatedArrays` to the `UpdateDescription` type returned in `ChangeStreamEvent`s. (SWIFT-1100). This was added to the spec via SPEC-1779 (corresponding [diff](https://github.com/mongodb/specifications/commit/07091ae92853530fddad2ac04f5f2641e78b27df)).
I synced the spec tests with the specs repo to bring in the new tests, which ended up bringing in a bunch of old tests we'd never synced either, in particular a bunch that were added via [SPEC-1505](https://jira.mongodb.org/browse/SPEC-1505) (for which our corresponding ticket is SWIFT-798). …
> SWIFT-1100, SWIFT-722, SWIFT-798 Catch up on recent change streams spec updates 

- .swiftlint.yml
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/MongoServerAPI.swift
Adds the public API required for versioned API support as defined [here](https://github.com/mongodb/specifications/blob/master/source/versioned-api/versioned-api.rst#mongoclient-changes).
In a future PR, `MongoClientOptions.ServerAPI` will gain a `withMongocServerAPI` method that will allow it to interoperate with libmongoc.
> SWIFT-1054 Add public API for versioned API

- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwiftSync/Exports.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedCollectionOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedDatabaseOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedOperation.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
- Tests/MongoSwiftSyncTests/UnifiedTests.swift
- Tests/MongoSwiftSyncTests/VersionedAPITests.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
Makes some updates to the runner that are prerequisites for decoding and running the versioned API tests:
* Support for decoding more types of operations we hadn't added before
* Support for a new type of test requirement, required server parameters
> SWIFT-1054 Unified test runner updates for versioned API

- .evergreen/config.yml
Add testing against the latest Swift 5.4 development snapshot to CI. Note we can only test on Linux atm because macOS 10.14 hosts don't support Swift 5.3+. 
I looked into starting to use the macOS 1.15 hosts but ran into [BUILD-13020](https://jira.mongodb.org/browse/BUILD-13020) which is hopefully a quick and easy fix.
Patch: https://spruce.mongodb.com/version/6067b26c5623436bc4d26601/
> SWIFT-1115 Test Swift 5.4 dev snapshot on Ubuntu

- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
`testIndexOptions` has started failing testing against server latest, because it turns out we were sending an option (index weights) that are only relevant for text indexes, even though the index we create is not a text index.
These used to just be ignored until [SERVER-54712](https://jira.mongodb.org/browse/SERVER-54712). Relatedly, I noticed that the same thing should probably be true for some other text index-specific options, which I filed [SERVER-55863](https://jira.mongodb.org/browse/SERVER-55863) about.
I've solved this by just moving these options out into a new test that actually creates a text index.
> Fix index tests to pass on server latest

- Tests/MongoSwiftTests/ConnectionStringTests.swift
https://spruce.mongodb.com/version/607064580305b974a7e7bb3e/tasks
this is the evergreen patch and there still seems to be an issue on oscp but I think patrick said it was okay
> Use ExtendedJSONEncoder in MongoConnectionString.testCodable

- Tests/Specs/versioned-api/tests/README.rst
- Tests/Specs/versioned-api/tests/test-commands-deprecation-errors.json
whoops, did this at some point last week but forgot to ever make a PR 🙂
patch: https://evergreen.mongodb.com/version/60887a880ae60623ca636ca8
> SWIFT-1178 Replace usages of 'acceptAPIVersion2' with 'acceptApiVersion2'

- Tests/MongoSwiftSyncTests/UnifiedTests.swift
- Tests/Specs/unified-test-format/tests/valid-fail/entity-client-apiVersion-unsupported.json
- Tests/Specs/unified-test-format/tests/valid-fail/operation-failure.json
- Tests/Specs/unified-test-format/tests/valid-pass/poc-retryable-writes.json
This brings in the test added by DRIVERS-1538 as well as a couple other newish test files/test file changes. I did not bother syncing anything that our runner isn't able to run yet due to schema version, or any of the "invalid" test files since we don't actually do anything with those. (Arguably we should delete those altogether since they exist for testing the schema, not testing runners?)
> SWIFT-1116 Sync in some unified runner tests

- .evergreen/config.yml
- .evergreen/run-atlas-tests.sh
- .evergreen/run-ocsp-test.sh
- .evergreen/run-tests.sh
This PR addresses a backlog of necessary Evergreen changes that have piled up recently:
- Since MongoDB 5.0 is no longer “latest” we need to test it separately
- Swift 5.4 has been released, so test against that and start testing against 5.5 development snapshots
- Stop testing on Ubuntu 16.04 and start testing on Ubuntu 20.04 (note that as discussed we don't test on < 4.4 on 20.04 now due to lack of specific builds and the end of generic builds w/ 4.0)
- Skip OCSP stapling tests on Ubuntu 18.04
- Use macOS 10.15 for all tests since it supports all of our Swift versions
complete patch: https://evergreen.mongodb.com/version/60baef80d1fe070beb0641c8
It looks kind of bad, but (I think) all the failures are expected:
- All tasks testing against 5.0 and latest, and the versioned API-specific …
> SWIFT-1208, SWIFT-1209, SWIFT-1221, SWIFT-1005 Various Evergreen configuration updates 

- README.md
Updated link to vapor example from 
https://github.com/mongodb/mongo-swift-driver/tree/main/Examples/ComplexVaporExample
to 
https://github.com/mongodb/mongo-swift-driver/tree/main/Examples/VaporExample
> SWIFT-1244: fixed 404 by updating link to vapor example

- README.md
- SECURITY.md
Rather than duplicating information from the MongoDB website (which may evolve with time) it seemed best to just reference that link and note the things here that are specific to our library (SSWG reqs) as compared to MongoDB products in general.
> SWIFT-1210 Add security policy per SSWG requirements

- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
This is failing due to CDRIVER-4077. I could have changed the test to test this in a different way e.g. explicitly killing the cursor via runCommand and ensuring a resume happens, however Kevin said he thinks his current work for load balancer (specifically CDRIVER-3653) may fix this issue, so I figured we can wait and try that first before rewriting the test.
> Skip testChangeStreamAutomaticResume against latest servers

- Examples/VaporExample/Package.swift
- Examples/VaporExample/Resources/Views/index.leaf
- Examples/VaporExample/Resources/Views/kitten.leaf
Depend on the new tag of MongoDBVapor, and pin js-bson for the same reasons we had to in the template as discussed in SWIFT-1264 (I updated that ticket to cover un-pinning here as well when the Node issue is resolved)
> Update Vapor example to depend on MongoDBVapor 1.0.0+ and pin js-bson version

- Sources/TestsCommon/CommonTestUtils.swift
- Tests/MongoSwiftSyncTests/CrudTests.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
- Tests/MongoSwiftSyncTests/MongoDatabaseTests.swift
- Tests/MongoSwiftSyncTests/ReadWriteConcernOperationTests.swift
- Tests/Specs/crud/tests/unified/aggregate-out-readConcern.json
- Tests/Specs/crud/tests/v1/read/aggregate-collation.json
- Tests/Specs/crud/tests/v1/read/aggregate-out.json
- Tests/Specs/crud/tests/v1/read/count-collation.json
- Tests/Specs/crud/tests/v1/read/distinct-collation.json
- Tests/Specs/crud/tests/v1/read/find-collation.json
- Tests/Specs/crud/tests/v1/write/bulkWrite-collation.json
- Tests/Specs/crud/tests/v1/write/deleteMany-collation.json
- Tests/Specs/crud/tests/v1/write/deleteOne-collation.json
- Tests/Specs/crud/tests/v1/write/findOneAndDelete-collation.json
- Tests/Specs/crud/tests/v1/write/findOneAndReplace-collation.json
- Tests/Specs/crud/tests/v1/write/findOneAndUpdate-collation.json
- Tests/Specs/crud/tests/v1/write/replaceOne-collation.json
- Tests/Specs/crud/tests/v1/write/updateMany-collation.json
- Tests/Specs/crud/tests/v1/write/updateOne-collation.json
SWIFT-1249 / SWIFT-1269
Serverless removed support for some features (`$out`, collation), so we needed to skip some tests and sync some spec tests.
> SWIFT-1249 / SWIFT-1269 Skip serverless tests that use disabled features

- Tests/MongoSwiftSyncTests/CrudTests.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/TestWriteModel.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedCollectionOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedOperation.swift
- Tests/Specs/crud/tests/unified/bulkWrite-insertOne-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/bulkWrite-replaceOne-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/bulkWrite-updateMany-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/bulkWrite-updateOne-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/findOneAndReplace-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/findOneAndUpdate-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/insertMany-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/insertOne-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/replaceOne-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/updateMany-dots_and_dollars.json
- Tests/Specs/crud/tests/unified/updateOne-dots_and_dollars.json
I already synced some of these tests as part of vendoring in libmongoc 1.18; this syncs the rest and makes some related test runner changes.
> SWIFT-1107 Sync "Mitigate pain of using field names with dots and dollars" tests

- Examples/Docs/Sources/AsyncExamples/main.swift
- Examples/Docs/Sources/SyncExamples/main.swift
We already had some versioned API examples from back around the time of the serverless beta. This updates them to match the form requested in SWIFT-1206, as well as adds a new example requested by SWIFT-1266.
> SWIFT-1206, SWIFT-1266: Update and expand versioned API examples

- Tests/MongoSwiftSyncTests/CommandMonitoringTests.swift
- Tests/MongoSwiftSyncTests/UnifiedTests.swift
These were being skipped because libmongoc had temporarily changed their cursor behavior to work around test failures. They have reverted those changes, and the tests have been updated (synced via #651) so we can unskip these now.
> SWIFT-1228 Unskip server kills cursor tests

- Sources/CLibMongoC/include/CLibMongoC_bson-version.h
- Sources/CLibMongoC/include/CLibMongoC_mongoc-version.h
- etc/generated_headers/bson-version.h
- etc/generated_headers/mongoc-version.h
- etc/vendor-libmongoc.sh
This includes some changes to the vendoring script as well as files in the `generated_headers/` directory, along with the resulting diff in `Sources/CLibMongoC/` from running the updating vendoring script.
> SWIFT-1122 Keep libmongoc version up-to-date in generated headers

- Examples/VaporExample/README.md
- Guides/TLS-Guide.md
- Sources/AtlasConnectivity/main.swift
- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/SDAM.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/MongoSwiftSyncTests/ClientSessionTests.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/SpecTest.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
- Tests/MongoSwiftSyncTests/SyncMongoClientTests.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
I looked into this while waiting around for Evergreen patches and it ended up being super small so figured we should just go ahead with it and close out the epic. 
Patch with added Atlas connectivity tasks since I changed the code in that target:  https://spruce.mongodb.com/version/610aed5dd6d80a1eba4406e9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> SWIFT-1212, SWIFT-1213: Remove oppressive language

- Tests/MongoSwiftSyncTests/CommandMonitoringTests.swift
- Tests/Specs/command-monitoring/tests/legacy/find.json
I code reviewed this spec update and confirmed the changes worked in Swift, so I figured I would just go ahead and put the changes into review.
> SWIFT-1303 Sync command monitoring tests to remove modifiers

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
- Tests/Specs/uri-options/tests/connection-options.json
- Tests/Specs/uri-options/tests/connection-pool-options.json
This is atop the `vendor-libmongoc`branch, will change base to `main` after that PR gets merged.
> SWIFT-1293 Add support for loadBalanced option

- Sources/MongoSwift/Operations/RunCommandOperation.swift
- Sources/TestsCommon/SpecTestUtils.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/FailPoint.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/Context.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/SpecialTestOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
This removes our (internal) support for targeting a particular host in `runCommand`, given that its bypassing of the server selection loop makes it susceptible to failure, and switches the unified test runner to use a client-per-mongos approach.
> SWIFT-1329 Use a client per mongos in unified test runner

- Sources/MongoSwift/Operations/ListCollectionsOperation.swift
- Sources/TestsCommon/APMUtils.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/LoadBalancerTests.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/CodableExtensions.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/EntityDescription.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/ExpectedEventsForClient.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/HasListableProperties.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedClientOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedCollectionOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedDatabaseOperations.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedOperation.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
[this is currently based on the Evergreen testing PR, I think GitHub will automatically update the base once that goes in]
This adds code to actually start running the new tests, as well as making some various unified runner / testing infrastructure changes to support it.
[patch](https://spruce.mongodb.com/version/612f9ed7850e612d5d269c78/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
> SWIFT-1326 Run load balancer spec tests 

- Sources/MongoSwift/ConnectionString.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
Makes the behavior for specifying maxPoolSize <= 0 in the connection string the same as it is when the option is provided via options struct (error).
> SWIFT-1214 Error on maxPoolSize <= 0 in connection string

- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SDAMTests.swift
Adds a prose test to confirm SDAM monitoring events look as one would expect.
> SWIFT-1327 add a prose test for SDAM monitoring in load balancer mode

- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/Operations/ListCollectionsOperation.swift
- Sources/MongoSwift/Operations/MongocCommandHelpers.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/MongoDatabaseTests.swift
Reimplements listCollections by running the command and creating a cursor from it. This is necessary because the libmongoc helper ignores the batchSize option.
> SWIFT-1322 Support batchSize option for listCollections

- Sources/MongoSwift/ClientSession.swift
As discovered via adding `leaks` to CI in my other PR. After this gets merged in I will rebase over there to get the new tasks passing.
> SWIFT-1347 Fix memory leak in tests caused by ClientSession.pinnedServerAddress

- .evergreen/install-tools.sh
- Package.resolved
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
Bumping the dependency versions in our Package.resolved file for NIO and the BSON library, and also the versions of the various tools we use on Evergreen.
> Update all library and tooling dependencies

- .evergreen/config.yml
- .evergreen/install-tools.sh
- Sources/MongoSwift/AsyncAwait/ClientSession+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoClient+AsyncAwait.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwiftSync/MongoClient.swift
- Tests/MongoSwiftTests/AsyncAwaitTests.swift
[this is atop #694, will rebase once that goes in]
Adds `async` versions of the API methods on these types and adds automatic cleanup for `ClientSession`s on Swift 5.5+. The cleanup was a slightly trickier refactor than I initially anticipated, some comments inline.
For now, due to the issue with the macOS Evergreen hosts, everything new is conditionally defined on Linux only. Whenever we can test on macOS again I will return and fix things up.
> SWIFT-1389 Add async/await APIs for MongoClient and ClientSession

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoConnectionString.swift
- Sources/MongoSwift/MongoCredential.swift
- Sources/MongoSwiftSync/Exports.swift
- Tests/MongoSwiftSyncTests/SyncAuthTests.swift
- Tests/MongoSwiftTests/AuthTests.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
Authentication options support for `MongoConnectionString`.
This PR also includes a commit to reapply the commit introducing the `MongoConnectionString` type. When this gets merged I'll keep the commits separate.
> SWIFT-1161 `MongoConnectionString` authentication options support

- .evergreen/config.yml
This issue only seems to come up on more recent server versions, I think because they have more tests for newer functionality.
It seems we can only set these on a per task level, so it will apply to these tasks on any OS. filed SWIFT-1410 so we remember to revert to the project's default task timeout of 30 minutes if/when the issue with the slow macOS hosts is resolved.
> Double timeouts for recent server sharded cluster tests

- etc/build-examples.sh
- etc/release.sh
This script previously assumed you were running it from `main`; this generalizes it to work regardless of branch. 
I'll cherry-pick this onto r1.2 as well.
> SWIFT-1414 Update release script to not only work on main

- Tests/MongoSwiftTests/AsyncAwaitTests.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
Adds a test that uses a `MongoClient` in parallel across a number of tasks to verify that works as we expect it to.
> SWIFT-1393 Add concurrent MongoClient usage test

- Sources/MongoSwift/AsyncAwait/ChangeStream+AsyncSequence.swift
- Sources/MongoSwift/AsyncAwait/ClientSession+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoClient+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+ChangeStreams+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+FindAndModify+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+Indexes+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+Read+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+Write+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCursor+AsyncSequence.swift
- Sources/MongoSwift/AsyncAwait/MongoDatabase+AsyncAwait.swift
- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/Operations/Operation.swift
- Tests/MongoSwiftTests/AsyncAwaitTestUtils.swift
- Tests/MongoSwiftTests/AsyncAwaitTests.swift
Due to CI issues, I initially defined all the new APIs on Linux only. This removes that code and switches to using `@available` annotations to indicate macOS compatibility instead.
That said, we still are not testing the new code in CI, since we have no macOS 12 hosts to test on. There is back-deployment support coming for concurrency in Xcode 13.2 (which will allow using concurrency features when targeting as low as macOS 10.15), however I'm still not sure if we'll be able to run tests then since I think Xcode 13.2 requires macOS 11.
Maybe I can get testing on those macOS 11 ARM hosts working by then, or alternatively we can look into getting a simple GH actions setup together to actually be able to run these tests on macOS in CI. I filed SWIFT-1421 about this
> SWIFT-1408 Remove conditional definition on Linux for async/await APIs

- .evergreen/config.yml
As described in SWIFT-1134 and linked tickets these always fail on macOS, likely due to cache clearing issues. Until we have time to figure out the proper way to clear the cache we should remove these from CI as they provide no value.
> Skip OCSP tests that always fail on macOS

- .github/ISSUE_TEMPLATE/bug_report.md
This migrates our legacy issue template to the new template   format, minor clean up.  Pending Further clean up clarifications.
> SWIFT-729: Update issue templates

- Sources/MongoSwift/AsyncAwait/MongoCursor+AsyncSequence.swift
- Sources/MongoSwift/MongoCursor.swift
I noticed from the benchmarks that iterating through a cursor's results one by one in the async API was about twice as a slow as doing so in the sync API. From using Xcode + Instruments with the time profiler instrument I was able to see that a lot of time was being spent calling `isAlive()`. 
That method and the looping behavior implemented using it is only useful when cursors are tailable, but as written we are currently paying the price of an extra call to `isAlive()` for every call to `next()`.
This updates the implementation of `MongoCursor.next()` so that in the common, non-tailable case we do not perform the unnecessary check, which saves us a journey across the `async`-futures boundary and a trip into the thread pool.
To improve the tailable cursor case (and the equivalent …
> Only check isAlive() for tailable cursors in async MongoCursor.next()

- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
On Swift 5.1, keywords such as `let` need to be escaped in argument lists, but this was changed in some intermediate Swift version, and on newer versions of Swift the escape generates a compiler warning.
Initially I thought I would use #if swift to define this code conditionally to avoid the warning on newer versions. However, this problem only happens when calling the initializer for `FindAndModifyOptions` which is an internal type, so it seemed simpler to just change the label and avoid branching logic.
> Get rid of compilation warnings for `let` on newer Swift versions

- .evergreen/config.yml
- .evergreen/get_latest_swift_patch.py
We now specify Swift versions of the form x.y, and at installation time query the Swift GitHub repo to find the latest matching release tag and write the value to a file.
We then add an expansion to set the SWIFT_VERSION variable used throughout the config/test scripts.
> Automatically use latest patch for each Swift release in CI

- Sources/MongoSwift/ServerSelection.swift
- Tests/MongoSwiftTests/ServerSelectionTests.swift
This PR adds the remaining unimplemented test work defined in the [server selection test plan](https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection-tests.rst).
> SWIFT-1464 Test server selection read preference validation

- .evergreen/config.yml
- Tests/MongoSwiftSyncTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/AsyncAwaitTestUtils.swift
- Tests/MongoSwiftTests/AsyncAwaitTests.swift
This didn't require any driver changes, but there was a prose test added so I went ahead with writing that. 
Prose test description:
```
To confirm that implicit sessions only allocate their server session after a successful connection checkout
* Create a MongoClient with the following options: ``maxPoolSize=1`` and ``retryWrites=true``
* Attach a command started listener that collects each command's lsid
* Initiate the following concurrent operations
* insertOne
* deleteOne
* updateOne
* bulkWrite ``[ { updateOne } ]``
* findOneAndDelete
* findOneAndUpdate
* findOneAndReplace
* find
* Wait for all operations to complete
* Assert that all commands contain the same lsid
```
> SWIFT-1383 Test that driver only creates implicit session after connection checkout

- .evergreen/configure-swift.sh
- .github/workflows/test-swift-concurrency.yml
- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoCursor.swift
- Tests/MongoSwiftTests/AsyncAwaitTestUtils.swift
- Tests/MongoSwiftTests/AsyncAwaitTests.swift
1) Fixes a bug where automatic cleanup in deinit would not happen for cursors/change streams/sessions on macOS < 12, even when concurrency is available
2) Adds a GitHub action to start running concurrency tests on macOS 11 + Xcode 13.2. Once [BUILD-14630](https://jira.mongodb.org/browse/BUILD-14630) is complete we can do this on Evergreen instead.
3) step 2 required removing the compiler directive to only define our concurrency-specific tests on Linux. doing so led our Evergreen tests to start failing, because despite being on macOS 10.15 where concurrency is now available, those still use a very old Xcode version whose bundled macOS SDK does not include the concurrency library. so while the Swift compiler can _import_ `_Concurrency`, the concurrency library is not actually there to …
> SWIFT-1510 Lower #available checks to run automatic cleanup in deinits to macOS 10.15+

- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoConnectionString.swift
- Tests/MongoSwiftTests/DNSSeedlistTests.swift
- Tests/MongoSwiftTests/MongoConnectionStringTests.swift
- Tests/Specs/initial-dns-seedlist-discovery/initial-dns-seedlist-discovery.rst
- Tests/Specs/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-replicaSet-errors.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-true-txt.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-zero-txt.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/load-balanced/srvMaxHosts-zero.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/replica-set/srv-service-name.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-conflicts_with_replicaSet-txt.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-conflicts_with_replicaSet.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-equal_to_srv_records.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-greater_than_srv_records.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-less_than_srv_records.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-zero-txt.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/replica-set/srvMaxHosts-zero.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/sharded/srvMaxHosts-equal_to_srv_records.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/sharded/srvMaxHosts-greater_than_srv_records.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/sharded/srvMaxHosts-less_than_srv_records.json
- Tests/Specs/initial-dns-seedlist-discovery/tests/sharded/srvMaxHosts-zero.json
This sync the latest copy of the initial DNS seedlist discovery tests and makes some modifications to the runner to support running them.
With this PR we can also close out SWIFT-1277 and SWIFT-1263 -- Isabel added Swift support for these options in the new connection string type and our latest vendor of libmongoc brought in the libmongoc support. We already have synced the corresponding URI options tests. I did notice that we didn't add these options to `MongoClientOptions` though so I went ahead with doing that here for completeness.
See mongodb/mongo-rust-driver#595 for equivalent Rust changes.
> SWIFT-1277, SWIFT-1263, SWIFT-1507 Sync latest initial DNS seedlist discovery tests

- Tests/MongoSwiftTests/DNSSeedlistTests.swift
It seems like I forgot to re-run these with auth on after adding the ping command. This led tests to start failing because the user we attempt to authenticate as doesn't exist.
Added logic to create the missing user if needed, inspired by corresponding Rust logic: https://github.com/mongodb/mongo-rust-driver/blob/0a50512aa0178f88bec2a1dc651f93e0b08a4f12/src/test/spec/initial_dns_seedlist_discovery.rs#L139-L157
> Create user so ping succeeds in DNS seedlist tests

- .evergreen/config.yml
- .evergreen/configure-swift.sh
- .evergreen/run-tests.sh
- Tests/MongoSwiftTests/AsyncAwaitTests.swift
SWIFT-1519
Updates so that the two latest versions we test against are 5.5 and 5.6, and renames the dev snapshot testing to 5.7-dev. 
successful evergreen patch: https://spruce.mongodb.com/version/62598ff4d1fe075aedb68b20/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> SWIFT-1519 Test Swift 5.6 in Evergreen

- .github/workflows/test-swift-concurrency.yml
Updates our GH action so we have some basic coverage on macOS 12. (macOS < 12 is covered by Evg testing).
> Test concurrency on macOS 12

- Tests/MongoSwiftTests/DNSSeedlistTests.swift
I had just copied this logic from the Rust test runner, but it was causing the tests to fail on MongoDB 3.6 because the `createUser` command didn't support the `mechanisms` field until 4.0.  It seems it's not necessary to even specify it at all to get the tests to pass and I'm actually not sure why the Rust code does that, so I just removed it.
> Fix DNS seedlist tests on 3.6

- Sources/MongoSwift/Operations/CountDocumentsOperation.swift
- Sources/MongoSwift/Operations/EstimatedDocumentCountOperation.swift
- Tests/MongoSwiftSyncTests/CrudTests.swift
- Tests/MongoSwiftSyncTests/ReadWriteConcernOperationTests.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedCollectionOperations.swift
- Tests/Specs/crud/tests/unified/countDocuments-comment.json
- Tests/Specs/crud/tests/unified/countDocuments-comment.yml
- Tests/Specs/crud/tests/unified/estimatedDocumentCount-comment.json
- Tests/Specs/crud/tests/unified/estimatedDocumentCount-comment.yml
Added `comment` field (of type `BSON`) to the EstimatedDocumentCountOptions and updated spec tests. In doing so, encountered some problems with the `UnifiedCollectionOperations` structs for `UnifiedCountDocuments` and `UnifiedEstimatedDocumentCount`. Changed those files to reflect the added comnment/modified tests. Some tests were still problematic and were temporarily excluded after discussion with @patrickfreed
> SWIFT-1514 Add 'comment' option to EstimatedDocumentCount and CountDocuments Options

- Sources/MongoSwift/ChangeStreamEvent.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/ExpectedEventsForClient.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/Matching.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
- Tests/Specs/change-streams/tests/unified/change-streams.json
- Tests/Specs/change-streams/tests/unified/change-streams.yml
Adding a field and impl for optional Date `wallTime`. Incorporated updated spec tests as outlined by `e1a513fe027afb7706485a1e79c53a96acc2ec22`. This involved upgrading the `UnifiedTestRunner` from `maxSchema` 1.5 to 1.7
Made associated changes and bumped version up. Excluded several tests that fail because of an old version of `libmongoc`, potentially resolved with beta vendoring
> SWIFT-1553: Always report `wallTime` in the change stream event output

- Sources/MongoSwift/MongoCollection+Indexes.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
Fixes https://github.com/mongodb/mongo-swift-driver/issues/768
> SWIFT-1616 ⁃ Impossible to create a text index with default name

- Tests/MongoSwiftTests/APMTests.swift
SWIFT-1630
This PR doubles the time the test waits for a batch of 60 inserts to complete from 5 seconds to 10 seconds after seeing some flakiness. I will say it is a bit concerning that we can't execute that many in the 5 seconds time, but I think that might have more to do with the hosts at our disposal rather than the driver.
> SWIFT-1630 Reduce flakiness of CommandStreamBufferPolicy test

- Sources/MongoSwift/ChangeStreamEvent.swift
- Sources/TestsCommon/APMUtils.swift
- Tests/MongoSwiftTests/AsyncAwaitTestUtils.swift
- Tests/MongoSwiftTests/AsyncAwaitTests.swift
- Tests/MongoSwiftTests/ChangeStreamTests.swift
- Tests/MongoSwiftTests/Failpoint.swift
- Tests/MongoSwiftTests/UnifiedTestRunner/SpecialTestOperations.swift
- Tests/Specs/change-streams/tests/unified/change-streams-clusterTime.json
- Tests/Specs/change-streams/tests/unified/change-streams-clusterTime.yml
- Tests/Specs/change-streams/tests/unified/change-streams-disambiguatedPaths.json
- Tests/Specs/change-streams/tests/unified/change-streams-disambiguatedPaths.yml
- Tests/Specs/change-streams/tests/unified/change-streams-showExpandedEvents.json
- Tests/Specs/change-streams/tests/unified/change-streams-showExpandedEvents.yml
- Tests/Specs/transactions/tests/unified/do-not-retry-read-in-transaction.json
- Tests/Specs/transactions/tests/unified/do-not-retry-read-in-transaction.yml
- Tests/Specs/transactions/tests/unified/mongos-unpin.yml
- Tests/Specs/transactions/tests/unified/retryable-abort-handshake.json
- Tests/Specs/transactions/tests/unified/retryable-abort-handshake.yml
- Tests/Specs/transactions/tests/unified/retryable-commit-handshake.json
- Tests/Specs/transactions/tests/unified/retryable-commit-handshake.yml
I picked up SWIFT-1610 which was a test sync; the sync also brought in the files from SWIFT-1378.
I also picked up SWIFT-1632 which I thought was just a test sync but it turns out we didn't have a `clusterTime` on `ChangeStreamEvent`. It seems like we decided against that in SWIFT-428 but now that there is a spec test it seems like we'd want to have one for compliance and parity with other drivers.
> SWIFT-1610, SWIFT-1378, SWIFT-1632: Spec tests sync + expose clusterTime on ChangeStreamEvent

- README.md
[https://www.mongodb.com/community/forums/t/updates-on-mongodb-swift-driver/240047](https://www.mongodb.com/community/forums/t/updates-on-mongodb-swift-driver/240047)
> Dear Swift Users,
> 
> TL;DR: MongoDB is halting development on our server-side Swift driver. We remain excited about Swift and will continue our development of our mobile Swift SDK.
> 
> We released our server-side Swift driver in 2020 as an open source project and are incredibly proud of the work that our engineering team has contributed to the Swift community over the last four years. Unfortunately, today we are announcing our decision to stop development of the MongoDB server-side Swift driver. We understand that this news may come as a disappointment to the community of current users.
> 
> There are still ways to use …
> Swift halt development announcement
