- Sources/MongoSwift/MongoSwift.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftBenchmarks/BenchmarkSetup.swift
- Tests/MongoSwiftTests/TestSetup.swift
https://jira.mongodb.org/browse/SWIFT-72
> SWIFT-72 hooks for libmongoc init and cleanup

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/Cursor.swift
- Sources/MongoSwift/SDAM.swift
https://jira.mongodb.org/browse/SWIFT-131
> SWIFT-131 Accept UnsafePointers when initializing BSON Document

- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/MongoError.swift
- Sources/MongoSwift/ReadPreference.swift
- Tests/MongoSwiftTests/DocumentTests.swift
- Tests/MongoSwiftTests/ReadPreferenceTests.swift
- Tests/MongoSwiftTests/XCTestManifests.swift
https://jira.mongodb.org/browse/SWIFT-31
> SWIFT-31: Implement ReadPreference type

- Sources/MongoSwift/BSON/BsonValue.swift
- Tests/MongoSwiftTests/DocumentTests.swift
https://jira.mongodb.org/browse/SWIFT-140
> SWIFT-140 When UUID binary subtype is provided, validate that data is 16 bytes

- Sources/MongoSwift/MongoCollection+Write.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
https://jira.mongodb.org/browse/SWIFT-162
> SWIFT-162 Allow for null document IDs in inserted and upserted documents

- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoError.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/XCTestManifests.swift
https://jira.mongodb.org/browse/SWIFT-147
Note: `bulkWrite-arrayFilters.json` now passes; however, I'd like to add additional tests before merging this (both in spec and non-spec form).
> SWIFT-147: Implement BulkWrite CRUD operation

- Sources/MongoSwift/MongoCollection+Write.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
https://jira.mongodb.org/browse/SWIFT-208
> SWIFT-208: CRUD methods return nil for unacknowledged write concern

- Sources/MongoSwift/BSON/Document+Sequence.swift
- Tests/MongoSwiftTests/Document+SequenceTests.swift
Fix isEmpty, and add a test checking behavior.
> SWIFT-230 fix isEmpty

- .travis.yml
https://jira.mongodb.org/browse/SWIFT-243 
Adds jobs for MacOS and Linux using Swift 4.2.
> SWIFT-243 Test Swift 4.2 on Travis 

- Sources/MongoSwift/SDAM.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
[SWIFT-266](https://jira.mongodb.org/browse/SWIFT-266)
> SWIFT-266 Nest TopologyType in TopologyDescription, and ServerType in ServerDescription

- Sources/MongoSwift/BSON/BSONValue.swift
[SWIFT-298](https://jira.mongodb.org/browse/SWIFT-298)
> SWIFT-298 Conform BSONNull to Equatable

- Sources/MongoSwift/MongoClient.swift
[SWIFT-317](https://jira.mongodb.org/browse/SWIFT-317)
> SWIFT-317 Fix retryWrites not set on client

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/BSON/BSONEncoder.swift
- Sources/MongoSwift/BSON/BSONValue.swift
- Sources/MongoSwift/BSON/Document+Sequence.swift
- Sources/MongoSwift/BSON/Document.swift
- Sources/MongoSwift/BSON/Overwritable.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+FindAndModify.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoCursor.swift
[SWIFT-308](https://jira.mongodb.org/browse/SWIFT-308)
This PR is a first pass. Once #203 is merged, I'll do another to make sure all the docs for `BSONEncoder`/`BSONDecoder` are up to date.
> SWIFT-308 Audit documentation of all functions that throw

- Tests/MongoSwiftTests/CodecTests.swift
[SWIFT-197](https://jira.mongodb.org/browse/SWIFT-197)
This corrects two usages of `UInt` that assumed a bitwidth of 64. As discussed in #swift it is very possible there are other tests that could fail on 32 bit that I missed, because as of now we have no way to actually run the tests on 32 bit.
> SWIFT-197 Ensure all tests involving Ints and UInts that need 64 bits are only run on 64-bit platforms

- Guides/Development.md
Updating this in preparation for our intern joining us in a few weeks. I think we've established enough norms around doing reviews that it's worth having a new section on.
Let me know if you think I've forgotten anything, or if you have any ideas for more learning Swift resources we could include.
> Update development guide

- Sources/MongoSwift/MongoCollection+BulkWrite.swift
[SWIFT-413](https://jira.mongodb.org/browse/SWIFT-413)
This PR exposes all the properties in the various `WriteModel`s.
I decided to delegate the options construction to `addToBulkWrite` since otherwise some of the properties would be computed and some wouldn't which would look strange in the documentation. Additionally, the options themselves are just there to ease encoding for passing to libmongoc, so they shouldn't bleed into our public api.
> SWIFT-413 Expose write model properties

- release/release.sh
edits based on using this today
> some small edits to release script

- Sources/MongoSwift/WriteConcern.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
* Check that the values for w and wtimeoutMS in WriteConcern are non-negative.
> SWIFT-503/validate w and wtimeoutMS

- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/MongoSwiftVersion.swift
- Sources/MongoSwift/Operations/DropCollectionOperation.swift
- Sources/MongoSwift/Operations/DropDatabaseOperation.swift
- Sources/MongoSwift/WriteConcern.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
* Added DropDatabaseOptions with a writeConcern optional that gets sent to mongoc
* Added DropCollectionOptions with a writeConcern optional that gets sent to mongoc
* Made wtimeoutMS in WriteConcern encode as an Int32
> Swift-412 Add drop database options

- Examples/Kitura/Package.swift
- Examples/Kitura/README.md
- Examples/Kitura/Sources/KituraExample/main.swift
- Examples/Perfect/Package.swift
- Examples/Perfect/README.md
- Examples/Perfect/Sources/PerfectExample/main.swift
- Examples/Vapor/Package.swift
- Examples/Vapor/README.md
- Examples/Vapor/Sources/VaporExample/main.swift
This adds a new very basic example project that uses Perfect, and updates the Vapor and Kitura examples to better match up with it.
Only kinda weird thing about this is that I could see someone potentially coming to our repo between when this gets merged and when we release pooling, and not having access to the threadsafe types yet 🤔 so maybe I'll wait to actually merge this until just before the release.
> SWIFT-403 Add an Example project using Perfect

- Guides/Multithreaded-Usage.md
Pretty simple new guide to using multithreading. Let me know if you have any ideas for other stuff to mention here.
> SWIFT-354 Add multithreading guide

- Sources/MongoSwift/APM.swift
- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/Counter.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+ChangeStreams.swift
- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/ListDatabasesOperation.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/MongoSwift/SDAM.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
This is the final PR for SWIFT-374 🎉 will make some comments inline
> SWIFT-374 Add pooled mode to ConnectionPool, and have ClientSessions store their source Connections

- .evergreen/config.yml
- .evergreen/install-dependencies.sh
- .evergreen/run-tests.sh
- Sources/MongoSwift/ConnectionPool.swift
- Tests/MongoSwiftTests/ChangeStreamTests.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/CommandMonitoringTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollection+IndexTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
- Tests/MongoSwiftTests/ReadPreferenceTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/RetryableWritesTests.swift
- Tests/MongoSwiftTests/SDAMMonitoringTests.swift
- Tests/MongoSwiftTests/SpecTestRunner/SpecTest.swift
- Tests/MongoSwiftTests/TestUtils.swift
This PR adds SSL versions of most of our test variants and does some internal refactoring in the tests to correctly set up SSL when running against those variants.
> SWIFT-531 Test against SSL variants on Evergreen

- Guides/Change-Streams.md
This covers basic usage of all of the method variants as well as resuming change streams. Let me know if you think there are any other examples that would be useful.
> SWIFT-453 Add a guide to using change streams in the driver

- Package.resolved
- Package.swift
- Sources/MongoSwift/MongoCollection.swift
- Sources/MongoSwift/MongoDatabase.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
[SWIFT-514](https://jira.mongodb.org/browse/SWIFT-514)
> SWIFT-514 Make MongoCollection and MongoDatabase structs

- Package.resolved
- Sources/MongoSwift/MongoCollection+BulkWrite.swift
- Sources/MongoSwift/MongoCollection+Write.swift
- Sources/MongoSwift/MongoError.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/CrudTests.swift
- Tests/MongoSwiftTests/MongoCollection+BulkWriteTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/SpecTestRunner/TestOperation.swift
- Tests/MongoSwiftTests/TestUtils.swift
Updates to the new enum-based API wwe discussed last week.
> SWIFT-516 Make BulkWriteOperation consistent with other Operation types

- Sources/MongoSwift/BSON/BSONDecoder.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/ListCollectionsOperation.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/MongoDatabaseTests.swift
Implement the collection enumeration spec using listCollections, listCollectionNames, and ListMongoCollections and add relevant tests.
JIRA ticket: https://jira.mongodb.org/browse/SWIFT-607
Evergreen: https://evergreen.mongodb.com/version/5d6843727742ae4163f0cdc2
> SWIFT-607 Implement collection enumeration spec

- Sources/MongoSwift/MongoError.swift
[SWIFT-633](https://jira.mongodb.org/browse/SWIFT-633)
This PR fixes some assertion failures we've been seeing on latest recently. It was due to a bug where we were parsing write concern errors via `parseMongocError`, which doesn't handle write / write concern errors. The output of such parsing was being discarded anyways though, so this fix won't have an effect on end users.
> SWIFT-633 Stop parsing write concern errors when extracting bulk write errors

- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/Operations/FindOperation.swift
- Sources/MongoSwiftSync/Exports.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/MongoCollectionTests.swift
- Tests/MongoSwiftTests/OptionsTests.swift
- Tests/MongoSwiftTests/ReadPreferenceTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernTests.swift
- Tests/MongoSwiftTests/RetryableReadsTests.swift
- Tests/MongoSwiftTests/SpecTestRunner/TestOperation.swift
Added a findOne method and tests.
> SWIFT-643 Add a findOne method

- Examples/KituraExample/Sources/KituraExample/main.swift
- Examples/PerfectExample/Sources/PerfectExample/main.swift
- Examples/VaporExample/Sources/VaporExample/main.swift
Undoing the changes from before since we are releasing this now.
> Share clients in examples

- Examples/Docker/README.md
Brings settings in line with those specified in the main project readme.
Some things to make sure you have:
any new warnings or errors.
functionality.
pre-existing tests.
the documentation as part of a separate commit).
> Update dependency revision requirements.

- .evergreen/config.yml
[SWIFT-690](https://jira.mongodb.org/browse/SWIFT-690)
Taken from the [go driver's config](https://github.com/mongodb/mongo-go-driver/blob/master/.evergreen/config.yml#L177).
[example patch](https://evergreen.mongodb.com/task/mongo_swift_driver_tests_all__os_fully_featured~ubuntu_18.04_swift_version~5.0_ssl~nossl_test_3.6_replica_set_patch_0d211072d7b37efa64a9fef0ecbdb66b6e35d5d5_5e0e4ed60ae606081514989d_20_01_02_20_14_50)
> SWIFT-690 Store mongod logs after evergreen runs

- .evergreen/config.yml
- .evergreen/install-dependencies.sh
- .evergreen/run-atlas-tests.sh
- .evergreen/run-tests.sh
Evergreen patch: https://evergreen.mongodb.com/version/5e1e4518562343482e160895 (failures are all due to timeout issue you've fixed in #383)
> SWIFT-634 add Swift 5.1 variants to evg

- .swiftlint.yml
- Package.resolved
- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/MongoSwiftSync/ClientSession.swift
- Sources/MongoSwiftSync/MongoClient.swift
- Sources/MongoSwiftSync/MongoCollection.swift
- Sources/MongoSwiftSync/MongoDatabase.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/ClientSessionTests.swift
- Tests/MongoSwiftSyncTests/SyncMongoClientTests.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
- Tests/MongoSwiftTests/ClientSessionTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
- Tests/MongoSwiftTests/ReadWriteConcernSpecTests.swift
> SWIFT-674 Make MongoSwift.ClientSession async, and implement MongoSwiftSync.ClientSession

- Sources/MongoSwift/Operations/FindOperation.swift
- Tests/BSONTests/CodecTests.swift
> SWIFT-439: Deprecate maxScan query option

- Sources/MongoSwift/MongoCollection+Indexes.swift
- Sources/MongoSwift/Operations/ListIndexesOperation.swift
> SWIFT-677: Reduce overhead of listIndexNames

- Sources/MongoSwift/TransactionOptions.swift
- Sources/MongoSwiftSync/Exports.swift
- Tests/MongoSwiftTests/OptionsTests.swift
> SWIFT-743 Implement TransactionOptions struct

- Guides/Change-Streams.md
- Guides/Error-Handling.md
> SWIFT-731 Update guides to focus on async API

- Sources/MongoSwift/ClientSession.swift
> SWIFT-746 Implement asynchronous transactions API

- .evergreen/config.yml
[patch](https://evergreen.mongodb.com/version/5e87707932f417510b73ae21)
> minor: add Ubuntu 16.04 to evergreen matrix

- Sources/MongoSwift/Operations/FindAndModifyOperation.swift
> SWIFT-779 Safe access to FindAndModifyOptions pointer

- Tests/MongoSwiftSyncTests/RetryableWritesTests.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/SpecTest.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/TestOperation.swift
- Tests/MongoSwiftSyncTests/SyncChangeStreamTests.swift
Opening a PR to get full ci run on subset of changes from #463
> minor: refactor test operations

- Sources/MongoSwift/ClientSession.swift
- Sources/MongoSwift/Operations/AbortTransactionOperation.swift
- Sources/MongoSwift/Operations/CommitTransactionOperation.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/MongoSwift/Operations/StartSessionOperation.swift
- Sources/MongoSwift/Operations/StartTransactionOperation.swift
Final SWIFT-779 PR. This makes `ClientSession'`s state private and guards access to its underlying libmongoc session and connection through helpers.
> SWIFT-779 Guard access to ClientSession internals

- Tests/MongoSwiftTests/MongoCursorTests.swift
Fixes a race in our test identified by TSan.
2 other races come up when running `testConnectionPoolSize`, which were fixed in a recently-resolved libmongoc ticket: [CDRIVER-3623](https://jira.mongodb.org/browse/CDRIVER-3623).
I brought this up in the team channel, but I think we should either figure out a way to get that backported / available to us somehow before 1.0, or we should just patch the fix into our vendored copy (it's [quite small](https://github.com/mongodb/mongo-c-driver/commit/ba1387f0b1b92e4533801e0269baea3817c95d06)).
I also opened a ticket about adding testing with TSan and ASan into CI. Seems important but I'd like to defer adding it to after 1.0 at this point.
Also, I ran the benchmark application + autocannon (hitting both `aggregate` and `distinct` endpoints many …
> SWIFT-761 Fix data race in cursor test

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
- Tests/MongoSwiftTests/MongoClientTests.swift
Adds support for specifying the heartbeatFrequencyMS option via options struct.
> SWIFT-905 Add heartbeatFrequencyMS option

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
Adds support for specifying serverSelectionTimeoutMS via options struct.
> SWIFT-907 Add serverSelectionTimeoutMS option

- Examples/Atlas/Package.swift
- Examples/Atlas/Sources/AtlasExamples/main.swift
- etc/build-examples.sh
[SWIFT-902](https://jira.mongodb.org/browse/SWIFT-902)
This PR adds examples to be used in the Atlas connection UI for both SCRAM and X509 authentication mechanisms.
> SWIFT-902 Add Atlas connection examples

- Guides/Error-Handling.md
- README.md
Adjusted insertedId into insertedID in README code example, also in the error handling guide. Related to SWIFT-850
Some things to make sure you have:
any new warnings or errors.
functionality.
pre-existing tests.
the documentation as part of a separate commit).
> Fixed typo for insertedId on code example and error-handling guide. 

- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedOperation.swift
- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestFile.swift
Adds another data structure, some comments inline
> SWIFT-913 Introduce a UnifiedOperation type

- Sources/MongoSwift/MongoCollection+Read.swift
- Sources/MongoSwift/MongoDatabase.swift
- Sources/MongoSwift/Operations/AggregateOperation.swift
- Sources/MongoSwiftSync/MongoCollection+Read.swift
- Sources/MongoSwiftSync/MongoDatabase.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/MongoDatabaseTests.swift
Adds the database aggregation helper. I modified the existing `AggragateOperation` file to also execute an aggregate on a `MongoDatabase`.
> SWIFT-577: Add the db.aggregate helper

- Sources/MongoSwift/MongoCollection+Indexes.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/MongoCollection+IndexTests.swift
adds the `wildcardProjection` option to `IndexOptions`
> SWIFT-481 Support index all paths

- etc/RELEASE.md
Added a step to file a DOCSP ticket outlining compatibility changes or lack thereof
> SWIFT-SWIFT-1053 ⁃ Update release checklist with step to file a DOCSP ticket

- Sources/CLibMongoC/bson/bson.c
- Sources/CLibMongoC/mongoc/mongoc-client-pool.c
- Sources/CLibMongoC/mongoc/mongoc-client-private.h
- Sources/CLibMongoC/mongoc/mongoc-client.c
- Sources/CLibMongoC/mongoc/mongoc-cluster-cyrus.c
- Sources/CLibMongoC/mongoc/mongoc-cluster-sspi.c
- Sources/CLibMongoC/mongoc/mongoc-collection.c
- Sources/CLibMongoC/mongoc/mongoc-socket.c
- Sources/CLibMongoC/mongoc/mongoc-stream-tls-openssl.c
- Sources/CLibMongoC/mongoc/mongoc-topology-background-monitoring.c
- Sources/CLibMongoC/mongoc/mongoc-topology-private.h
- Sources/CLibMongoC/mongoc/mongoc-topology.c
- etc/vendor-libmongoc.sh
Vendors in the latest libmongoc version.
all green minus the random failure due to what we discussed in the channel. I'm discussing now with folks in the unified test runner channel how to fix that, but I don't think we need to block the upgrade on that
https://evergreen.mongodb.com/version/601cc5843066152b49a5bc72
> SWIFT-1092 Vendor in libmongoc 1.17.4

- Sources/MongoSwift/ConnectionString.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Sources/TestsCommon/ServerVersion.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftSyncTests/SpecTestRunner/FailPoint.swift
- Tests/MongoSwiftSyncTests/SyncMongoClientTests.swift
- Tests/MongoSwiftSyncTests/SyncTestUtils.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
SWIFT-904 Add connectTimeoutMS option to MongoClientOptions
> SWIFT-904 Add connectTimeoutMS option to MongoClientOptions

- Sources/MongoSwift/MongoConnectionString.swift
- Sources/MongoSwift/SDAM.swift
- Sources/MongoSwiftSync/Exports.swift
- Tests/LinuxMain.swift
- Tests/MongoSwiftTests/ConnectionStringTests.swift
SWIFT-1160 created MongoConnectionString.swift 
I just created tempOptions so the linter would stop complaining about unused variables
> SWIFT-1160 Introduce new MongoConnectionString type

- Examples/Docs/Sources/AsyncExamples/main.swift
- Examples/Docs/Sources/SyncExamples/main.swift
- Sources/MongoSwift/MongoServerAPI.swift
- Sources/MongoSwiftSync/MongoDatabase.swift
https://jira.mongodb.org/browse/SWIFT-1090
Using my other PR as the base branch since I developed/tested these atop that.
> SWIFT-1090 Add code examples for versioned API docs

- README.md
- etc/release.sh
Copying over my work from the Vapor library
> Automate updating version string in README

- Tests/MongoSwiftSyncTests/UnifiedTestRunner/UnifiedTestRunner.swift
Decreases the frequency with which we run `killAllSessions` to just after failed tests, rather than at the start of every suite and after every suite.
Sample patch here: https://evergreen.mongodb.com/version/6111b473c9ec44484753fc97
There is likely still some possibility of flakiness here, but given the failures did not show up on any of the tasks in that patch I think this has hopefully at least decreased the frequency.
I left the transactions test runner alone for now, since those issues have not been coming up as much, and hopefully DRIVERS-1539 will be done fairly soon to cut down on how much we need to run it there too.
> Run killAllSessions less frequently in unified test runner

- README.md
> Update SSWG badge and fix broken links

- .evergreen/config.yml
> SWIFT-1406 Don't use git:// for cloning drivers-evergreen-tools

- Sources/MongoSwift/AsyncAwait/MongoDatabase+AsyncAwait.swift
- Tests/MongoSwiftTests/AsyncAwaitTests.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
Adds async/await versions of `MongoDatabase` API methods. This is atop #697, will rebase after.
> SWIFT-1390 Add async/await MongoDatabase API

- .evergreen/config.yml
Same as #702 but targeting the 1.2 branch.
> [backport] Double timeouts for recent server sharded cluster tests

- Sources/MongoSwift/AsyncAwait/ClientSession+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoClient+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+ChangeStreams+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+FindAndModify+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+Indexes+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+Read+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+Write+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoDatabase+AsyncAwait.swift
- Sources/TestsCommon/CommonTestUtils.swift
- Tests/MongoSwiftTests/AsyncAwaitTestUtils.swift
- Tests/MongoSwiftTests/AsyncAwaitTests.swift
This is a large PR but most of the content is quite straightforward, just more async versions of existing API methods, so hopefully it is not too painful to review.
> SWIFT-1391 Add MongoCollection async/await API

- Sources/MongoSwift/AsyncAwait/ChangeStream+AsyncSequence.swift
- Sources/MongoSwift/AsyncAwait/MongoCollection+ChangeStreams+AsyncAwait.swift
- Sources/MongoSwift/AsyncAwait/MongoCursor+AsyncSequence.swift
- Sources/MongoSwift/ChangeStream.swift
- Sources/MongoSwift/MongoCursor.swift
- Sources/MongoSwift/Operations/Operation.swift
- Sources/TestsCommon/APMUtils.swift
- Tests/MongoSwiftTests/AsyncAwaitTestUtils.swift
- Tests/MongoSwiftTests/AsyncAwaitTests.swift
- Tests/MongoSwiftTests/AsyncTestUtils.swift
Add async versions of the APIs for these types, including conformance to `AsyncSequence`.
> SWIFT-1392 Add MongoCursor and ChangeStream async/await APIs

- etc/update-spec-test.sh
This is basically a clone of the script from the rust driver, with a few minor changes
> SWIFT-1431: Add a script to sync specification file

- .github/workflows/issue_assignment.yml
Some things to make sure you have:
any new warnings or errors.
functionality.
pre-existing tests.
the documentation as part of a separate commit).
> SWIFT-1439

- Sources/MongoSwift/ConnectionPool.swift
- Sources/MongoSwift/MongoClient.swift
- Sources/MongoSwift/MongoConnectionString.swift
- Sources/MongoSwift/MongoCredential.swift
- Tests/MongoSwiftTests/AuthTests.swift
- Tests/MongoSwiftTests/DNSSeedlistTests.swift
- Tests/MongoSwiftTests/MongoConnectionStringTests.swift
The patch on this PR has been updated to run all build variants.
> Fix `MongoConnectionString` errors

- Guides/Change-Streams-Guide.md
- Guides/Codable-Guide.md
- Guides/Error-Handling-Guide.md
- Guides/Multithreaded-Usage.md
- Guides/Transactions-Guide.md
- README.md
Update various examples and docs to show using the new APIs.
> SWIFT-1395 Update driver docs for async/await

- Sources/MongoSwift/ServerSelection.swift
- Tests/MongoSwiftTests/ServerSelectionTests.swift
Updates the `selectServer` method to use an async sleep as a placeholder for a topology check.
> Make `selectServer` async

- .evergreen/install-tools.sh
- Examples/KituraExample/Sources/KituraExample/main.swift
- Tests/MongoSwiftTests/AsyncAwaitTestUtils.swift
Updates the versions of SwiftFormat, SwiftLint, and Sourcery we use in CI.
> Update tool versions

- .github/workflows/close_stale_issues.yml
- .github/workflows/issue_assignment.yml
- .github/workflows/remove_labels.yml
Some things to make sure you have:
any new warnings or errors.
functionality.
pre-existing tests.
the documentation as part of a separate commit).
> SWIFT-1520/Issue assignment update
